/*
GateForge IAM API

Public HTTP API for GateForge IAM — OpenID Connect / OAuth2 endpoints at the server root, plus the application JSON API under `/api/v1` (auth, MFA, WebAuthn, tenants, and platform admin). Success responses for `/api/v1` use a `{meta, data}` envelope. OAuth token and userinfo errors use `{error, error_description}`.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


type WebAuthnAPI interface {

	/*
	FinishWebauthnLogin Finish passkey login

	Verifies the assertion. On success without MFA: returns `data` as LoginResponse and sets `iam_session` cookie. When MFA is enabled for the user, returns MFALoginChallengeResponse in `data` instead (then call POST /api/v1/mfa/challenge/verify).

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiFinishWebauthnLoginRequest
	*/
	FinishWebauthnLogin(ctx context.Context) ApiFinishWebauthnLoginRequest

	// FinishWebauthnLoginExecute executes the request
	//  @return LoginResultEnvelope
	FinishWebauthnLoginExecute(r ApiFinishWebauthnLoginRequest) (*LoginResultEnvelope, *http.Response, error)

	/*
	FinishWebauthnRegister Finish passkey registration

	Verifies the attestation and stores the passkey for the current user.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiFinishWebauthnRegisterRequest
	*/
	FinishWebauthnRegister(ctx context.Context) ApiFinishWebauthnRegisterRequest

	// FinishWebauthnRegisterExecute executes the request
	//  @return EmptyDataEnvelope
	FinishWebauthnRegisterExecute(r ApiFinishWebauthnRegisterRequest) (*EmptyDataEnvelope, *http.Response, error)

	/*
	ListWebauthnCredentials List registered passkeys

	Returns passkeys registered for the current user (device label and created date only).

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiListWebauthnCredentialsRequest
	*/
	ListWebauthnCredentials(ctx context.Context) ApiListWebauthnCredentialsRequest

	// ListWebauthnCredentialsExecute executes the request
	//  @return WebauthnCredentialListEnvelope
	ListWebauthnCredentialsExecute(r ApiListWebauthnCredentialsRequest) (*WebauthnCredentialListEnvelope, *http.Response, error)

	/*
	StartWebauthnLogin Begin passkey login

	Returns WebAuthn PublicKeyCredentialRequestOptions as `data.options` and a `session_token` for login/finish. Public endpoint (rate limited).

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiStartWebauthnLoginRequest
	*/
	StartWebauthnLogin(ctx context.Context) ApiStartWebauthnLoginRequest

	// StartWebauthnLoginExecute executes the request
	//  @return WebauthnLoginStartEnvelope
	StartWebauthnLoginExecute(r ApiStartWebauthnLoginRequest) (*WebauthnLoginStartEnvelope, *http.Response, error)

	/*
	StartWebauthnRegister Begin passkey registration

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiStartWebauthnRegisterRequest
	*/
	StartWebauthnRegister(ctx context.Context) ApiStartWebauthnRegisterRequest

	// StartWebauthnRegisterExecute executes the request
	//  @return WebauthnRegisterStartEnvelope
	StartWebauthnRegisterExecute(r ApiStartWebauthnRegisterRequest) (*WebauthnRegisterStartEnvelope, *http.Response, error)
}

// WebAuthnAPIService WebAuthnAPI service
type WebAuthnAPIService service

type ApiFinishWebauthnLoginRequest struct {
	ctx context.Context
	ApiService WebAuthnAPI
	webauthnLoginFinishRequest *WebauthnLoginFinishRequest
}

func (r ApiFinishWebauthnLoginRequest) WebauthnLoginFinishRequest(webauthnLoginFinishRequest WebauthnLoginFinishRequest) ApiFinishWebauthnLoginRequest {
	r.webauthnLoginFinishRequest = &webauthnLoginFinishRequest
	return r
}

func (r ApiFinishWebauthnLoginRequest) Execute() (*LoginResultEnvelope, *http.Response, error) {
	return r.ApiService.FinishWebauthnLoginExecute(r)
}

/*
FinishWebauthnLogin Finish passkey login

Verifies the assertion. On success without MFA: returns `data` as LoginResponse and sets `iam_session` cookie. When MFA is enabled for the user, returns MFALoginChallengeResponse in `data` instead (then call POST /api/v1/mfa/challenge/verify).

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiFinishWebauthnLoginRequest
*/
func (a *WebAuthnAPIService) FinishWebauthnLogin(ctx context.Context) ApiFinishWebauthnLoginRequest {
	return ApiFinishWebauthnLoginRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return LoginResultEnvelope
func (a *WebAuthnAPIService) FinishWebauthnLoginExecute(r ApiFinishWebauthnLoginRequest) (*LoginResultEnvelope, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *LoginResultEnvelope
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "WebAuthnAPIService.FinishWebauthnLogin")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/webauthn/login/finish"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.webauthnLoginFinishRequest == nil {
		return localVarReturnValue, nil, reportError("webauthnLoginFinishRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.webauthnLoginFinishRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiFinishWebauthnRegisterRequest struct {
	ctx context.Context
	ApiService WebAuthnAPI
	webauthnRegisterFinishRequest *WebauthnRegisterFinishRequest
}

func (r ApiFinishWebauthnRegisterRequest) WebauthnRegisterFinishRequest(webauthnRegisterFinishRequest WebauthnRegisterFinishRequest) ApiFinishWebauthnRegisterRequest {
	r.webauthnRegisterFinishRequest = &webauthnRegisterFinishRequest
	return r
}

func (r ApiFinishWebauthnRegisterRequest) Execute() (*EmptyDataEnvelope, *http.Response, error) {
	return r.ApiService.FinishWebauthnRegisterExecute(r)
}

/*
FinishWebauthnRegister Finish passkey registration

Verifies the attestation and stores the passkey for the current user.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiFinishWebauthnRegisterRequest
*/
func (a *WebAuthnAPIService) FinishWebauthnRegister(ctx context.Context) ApiFinishWebauthnRegisterRequest {
	return ApiFinishWebauthnRegisterRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return EmptyDataEnvelope
func (a *WebAuthnAPIService) FinishWebauthnRegisterExecute(r ApiFinishWebauthnRegisterRequest) (*EmptyDataEnvelope, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *EmptyDataEnvelope
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "WebAuthnAPIService.FinishWebauthnRegister")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/webauthn/register/finish"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.webauthnRegisterFinishRequest == nil {
		return localVarReturnValue, nil, reportError("webauthnRegisterFinishRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.webauthnRegisterFinishRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiListWebauthnCredentialsRequest struct {
	ctx context.Context
	ApiService WebAuthnAPI
	page *int32
	pageSize *int32
}

// Page number
func (r ApiListWebauthnCredentialsRequest) Page(page int32) ApiListWebauthnCredentialsRequest {
	r.page = &page
	return r
}

// Page size
func (r ApiListWebauthnCredentialsRequest) PageSize(pageSize int32) ApiListWebauthnCredentialsRequest {
	r.pageSize = &pageSize
	return r
}

func (r ApiListWebauthnCredentialsRequest) Execute() (*WebauthnCredentialListEnvelope, *http.Response, error) {
	return r.ApiService.ListWebauthnCredentialsExecute(r)
}

/*
ListWebauthnCredentials List registered passkeys

Returns passkeys registered for the current user (device label and created date only).

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiListWebauthnCredentialsRequest
*/
func (a *WebAuthnAPIService) ListWebauthnCredentials(ctx context.Context) ApiListWebauthnCredentialsRequest {
	return ApiListWebauthnCredentialsRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return WebauthnCredentialListEnvelope
func (a *WebAuthnAPIService) ListWebauthnCredentialsExecute(r ApiListWebauthnCredentialsRequest) (*WebauthnCredentialListEnvelope, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *WebauthnCredentialListEnvelope
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "WebAuthnAPIService.ListWebauthnCredentials")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/webauthn/credentials"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.page != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "page", r.page, "form", "")
	}
	if r.pageSize != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "page_size", r.pageSize, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiStartWebauthnLoginRequest struct {
	ctx context.Context
	ApiService WebAuthnAPI
	webauthnLoginStartRequest *WebauthnLoginStartRequest
}

func (r ApiStartWebauthnLoginRequest) WebauthnLoginStartRequest(webauthnLoginStartRequest WebauthnLoginStartRequest) ApiStartWebauthnLoginRequest {
	r.webauthnLoginStartRequest = &webauthnLoginStartRequest
	return r
}

func (r ApiStartWebauthnLoginRequest) Execute() (*WebauthnLoginStartEnvelope, *http.Response, error) {
	return r.ApiService.StartWebauthnLoginExecute(r)
}

/*
StartWebauthnLogin Begin passkey login

Returns WebAuthn PublicKeyCredentialRequestOptions as `data.options` and a `session_token` for login/finish. Public endpoint (rate limited).

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiStartWebauthnLoginRequest
*/
func (a *WebAuthnAPIService) StartWebauthnLogin(ctx context.Context) ApiStartWebauthnLoginRequest {
	return ApiStartWebauthnLoginRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return WebauthnLoginStartEnvelope
func (a *WebAuthnAPIService) StartWebauthnLoginExecute(r ApiStartWebauthnLoginRequest) (*WebauthnLoginStartEnvelope, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *WebauthnLoginStartEnvelope
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "WebAuthnAPIService.StartWebauthnLogin")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/webauthn/login/start"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.webauthnLoginStartRequest == nil {
		return localVarReturnValue, nil, reportError("webauthnLoginStartRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.webauthnLoginStartRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiStartWebauthnRegisterRequest struct {
	ctx context.Context
	ApiService WebAuthnAPI
	webauthnRegisterStartRequest *WebauthnRegisterStartRequest
}

func (r ApiStartWebauthnRegisterRequest) WebauthnRegisterStartRequest(webauthnRegisterStartRequest WebauthnRegisterStartRequest) ApiStartWebauthnRegisterRequest {
	r.webauthnRegisterStartRequest = &webauthnRegisterStartRequest
	return r
}

func (r ApiStartWebauthnRegisterRequest) Execute() (*WebauthnRegisterStartEnvelope, *http.Response, error) {
	return r.ApiService.StartWebauthnRegisterExecute(r)
}

/*
StartWebauthnRegister Begin passkey registration

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiStartWebauthnRegisterRequest
*/
func (a *WebAuthnAPIService) StartWebauthnRegister(ctx context.Context) ApiStartWebauthnRegisterRequest {
	return ApiStartWebauthnRegisterRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return WebauthnRegisterStartEnvelope
func (a *WebAuthnAPIService) StartWebauthnRegisterExecute(r ApiStartWebauthnRegisterRequest) (*WebauthnRegisterStartEnvelope, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *WebauthnRegisterStartEnvelope
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "WebAuthnAPIService.StartWebauthnRegister")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/webauthn/register/start"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.webauthnRegisterStartRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
