/*
GateForge IAM API

Public HTTP API for GateForge IAM — OpenID Connect / OAuth2 endpoints at the server root, plus the application JSON API under `/api/v1` (auth, MFA, WebAuthn, tenants, and platform admin). Success responses for `/api/v1` use a `{meta, data}` envelope. OAuth token and userinfo errors use `{error, error_description}`.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AdminUserMembershipResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminUserMembershipResponse{}

// AdminUserMembershipResponse struct for AdminUserMembershipResponse
type AdminUserMembershipResponse struct {
	TenantId *string `json:"tenant_id,omitempty"`
	TenantName *string `json:"tenant_name,omitempty"`
	Role *string `json:"role,omitempty"`
	Status *string `json:"status,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AdminUserMembershipResponse AdminUserMembershipResponse

// NewAdminUserMembershipResponse instantiates a new AdminUserMembershipResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminUserMembershipResponse() *AdminUserMembershipResponse {
	this := AdminUserMembershipResponse{}
	return &this
}

// NewAdminUserMembershipResponseWithDefaults instantiates a new AdminUserMembershipResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminUserMembershipResponseWithDefaults() *AdminUserMembershipResponse {
	this := AdminUserMembershipResponse{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *AdminUserMembershipResponse) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminUserMembershipResponse) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *AdminUserMembershipResponse) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *AdminUserMembershipResponse) SetTenantId(v string) {
	o.TenantId = &v
}

// GetTenantName returns the TenantName field value if set, zero value otherwise.
func (o *AdminUserMembershipResponse) GetTenantName() string {
	if o == nil || IsNil(o.TenantName) {
		var ret string
		return ret
	}
	return *o.TenantName
}

// GetTenantNameOk returns a tuple with the TenantName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminUserMembershipResponse) GetTenantNameOk() (*string, bool) {
	if o == nil || IsNil(o.TenantName) {
		return nil, false
	}
	return o.TenantName, true
}

// HasTenantName returns a boolean if a field has been set.
func (o *AdminUserMembershipResponse) HasTenantName() bool {
	if o != nil && !IsNil(o.TenantName) {
		return true
	}

	return false
}

// SetTenantName gets a reference to the given string and assigns it to the TenantName field.
func (o *AdminUserMembershipResponse) SetTenantName(v string) {
	o.TenantName = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *AdminUserMembershipResponse) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminUserMembershipResponse) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *AdminUserMembershipResponse) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *AdminUserMembershipResponse) SetRole(v string) {
	o.Role = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *AdminUserMembershipResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminUserMembershipResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *AdminUserMembershipResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *AdminUserMembershipResponse) SetStatus(v string) {
	o.Status = &v
}

func (o AdminUserMembershipResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminUserMembershipResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenant_id"] = o.TenantId
	}
	if !IsNil(o.TenantName) {
		toSerialize["tenant_name"] = o.TenantName
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AdminUserMembershipResponse) UnmarshalJSON(data []byte) (err error) {
	varAdminUserMembershipResponse := _AdminUserMembershipResponse{}

	err = json.Unmarshal(data, &varAdminUserMembershipResponse)

	if err != nil {
		return err
	}

	*o = AdminUserMembershipResponse(varAdminUserMembershipResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tenant_id")
		delete(additionalProperties, "tenant_name")
		delete(additionalProperties, "role")
		delete(additionalProperties, "status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAdminUserMembershipResponse struct {
	value *AdminUserMembershipResponse
	isSet bool
}

func (v NullableAdminUserMembershipResponse) Get() *AdminUserMembershipResponse {
	return v.value
}

func (v *NullableAdminUserMembershipResponse) Set(val *AdminUserMembershipResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminUserMembershipResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminUserMembershipResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminUserMembershipResponse(val *AdminUserMembershipResponse) *NullableAdminUserMembershipResponse {
	return &NullableAdminUserMembershipResponse{value: val, isSet: true}
}

func (v NullableAdminUserMembershipResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminUserMembershipResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


