/*
GateForge IAM API

Public HTTP API for GateForge IAM — OpenID Connect / OAuth2 endpoints at the server root, plus the application JSON API under `/api/v1` (auth, MFA, WebAuthn, tenants, and platform admin). Success responses for `/api/v1` use a `{meta, data}` envelope. OAuth token and userinfo errors use `{error, error_description}`.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the AdminCreateTenantRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminCreateTenantRequest{}

// AdminCreateTenantRequest struct for AdminCreateTenantRequest
type AdminCreateTenantRequest struct {
	Name string `json:"name"`
	Domain *string `json:"domain,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AdminCreateTenantRequest AdminCreateTenantRequest

// NewAdminCreateTenantRequest instantiates a new AdminCreateTenantRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminCreateTenantRequest(name string) *AdminCreateTenantRequest {
	this := AdminCreateTenantRequest{}
	this.Name = name
	return &this
}

// NewAdminCreateTenantRequestWithDefaults instantiates a new AdminCreateTenantRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminCreateTenantRequestWithDefaults() *AdminCreateTenantRequest {
	this := AdminCreateTenantRequest{}
	return &this
}

// GetName returns the Name field value
func (o *AdminCreateTenantRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AdminCreateTenantRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AdminCreateTenantRequest) SetName(v string) {
	o.Name = v
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *AdminCreateTenantRequest) GetDomain() string {
	if o == nil || IsNil(o.Domain) {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminCreateTenantRequest) GetDomainOk() (*string, bool) {
	if o == nil || IsNil(o.Domain) {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *AdminCreateTenantRequest) HasDomain() bool {
	if o != nil && !IsNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *AdminCreateTenantRequest) SetDomain(v string) {
	o.Domain = &v
}

func (o AdminCreateTenantRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminCreateTenantRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Domain) {
		toSerialize["domain"] = o.Domain
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AdminCreateTenantRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdminCreateTenantRequest := _AdminCreateTenantRequest{}

	err = json.Unmarshal(data, &varAdminCreateTenantRequest)

	if err != nil {
		return err
	}

	*o = AdminCreateTenantRequest(varAdminCreateTenantRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "domain")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAdminCreateTenantRequest struct {
	value *AdminCreateTenantRequest
	isSet bool
}

func (v NullableAdminCreateTenantRequest) Get() *AdminCreateTenantRequest {
	return v.value
}

func (v *NullableAdminCreateTenantRequest) Set(val *AdminCreateTenantRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminCreateTenantRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminCreateTenantRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminCreateTenantRequest(val *AdminCreateTenantRequest) *NullableAdminCreateTenantRequest {
	return &NullableAdminCreateTenantRequest{value: val, isSet: true}
}

func (v NullableAdminCreateTenantRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminCreateTenantRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


