/*
GateForge IAM API

Public HTTP API for GateForge IAM — OpenID Connect / OAuth2 endpoints at the server root, plus the application JSON API under `/api/v1` (auth, MFA, WebAuthn, tenants, and platform admin). Success responses for `/api/v1` use a `{meta, data}` envelope. OAuth token and userinfo errors use `{error, error_description}`.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AdminIdentityProviderResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminIdentityProviderResponse{}

// AdminIdentityProviderResponse struct for AdminIdentityProviderResponse
type AdminIdentityProviderResponse struct {
	TenantId *string `json:"tenant_id,omitempty"`
	Provider *string `json:"provider,omitempty"`
	Name *string `json:"name,omitempty"`
	Enabled *bool `json:"enabled,omitempty"`
	Configured *bool `json:"configured,omitempty"`
	OauthClientId *string `json:"oauth_client_id,omitempty"`
	OauthClientSecretSet *bool `json:"oauth_client_secret_set,omitempty"`
	RedirectUri *string `json:"redirect_uri,omitempty"`
	SetupConsoleUrl *string `json:"setup_console_url,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AdminIdentityProviderResponse AdminIdentityProviderResponse

// NewAdminIdentityProviderResponse instantiates a new AdminIdentityProviderResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminIdentityProviderResponse() *AdminIdentityProviderResponse {
	this := AdminIdentityProviderResponse{}
	return &this
}

// NewAdminIdentityProviderResponseWithDefaults instantiates a new AdminIdentityProviderResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminIdentityProviderResponseWithDefaults() *AdminIdentityProviderResponse {
	this := AdminIdentityProviderResponse{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *AdminIdentityProviderResponse) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminIdentityProviderResponse) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *AdminIdentityProviderResponse) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *AdminIdentityProviderResponse) SetTenantId(v string) {
	o.TenantId = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *AdminIdentityProviderResponse) GetProvider() string {
	if o == nil || IsNil(o.Provider) {
		var ret string
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminIdentityProviderResponse) GetProviderOk() (*string, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *AdminIdentityProviderResponse) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given string and assigns it to the Provider field.
func (o *AdminIdentityProviderResponse) SetProvider(v string) {
	o.Provider = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AdminIdentityProviderResponse) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminIdentityProviderResponse) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AdminIdentityProviderResponse) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AdminIdentityProviderResponse) SetName(v string) {
	o.Name = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *AdminIdentityProviderResponse) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminIdentityProviderResponse) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *AdminIdentityProviderResponse) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *AdminIdentityProviderResponse) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetConfigured returns the Configured field value if set, zero value otherwise.
func (o *AdminIdentityProviderResponse) GetConfigured() bool {
	if o == nil || IsNil(o.Configured) {
		var ret bool
		return ret
	}
	return *o.Configured
}

// GetConfiguredOk returns a tuple with the Configured field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminIdentityProviderResponse) GetConfiguredOk() (*bool, bool) {
	if o == nil || IsNil(o.Configured) {
		return nil, false
	}
	return o.Configured, true
}

// HasConfigured returns a boolean if a field has been set.
func (o *AdminIdentityProviderResponse) HasConfigured() bool {
	if o != nil && !IsNil(o.Configured) {
		return true
	}

	return false
}

// SetConfigured gets a reference to the given bool and assigns it to the Configured field.
func (o *AdminIdentityProviderResponse) SetConfigured(v bool) {
	o.Configured = &v
}

// GetOauthClientId returns the OauthClientId field value if set, zero value otherwise.
func (o *AdminIdentityProviderResponse) GetOauthClientId() string {
	if o == nil || IsNil(o.OauthClientId) {
		var ret string
		return ret
	}
	return *o.OauthClientId
}

// GetOauthClientIdOk returns a tuple with the OauthClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminIdentityProviderResponse) GetOauthClientIdOk() (*string, bool) {
	if o == nil || IsNil(o.OauthClientId) {
		return nil, false
	}
	return o.OauthClientId, true
}

// HasOauthClientId returns a boolean if a field has been set.
func (o *AdminIdentityProviderResponse) HasOauthClientId() bool {
	if o != nil && !IsNil(o.OauthClientId) {
		return true
	}

	return false
}

// SetOauthClientId gets a reference to the given string and assigns it to the OauthClientId field.
func (o *AdminIdentityProviderResponse) SetOauthClientId(v string) {
	o.OauthClientId = &v
}

// GetOauthClientSecretSet returns the OauthClientSecretSet field value if set, zero value otherwise.
func (o *AdminIdentityProviderResponse) GetOauthClientSecretSet() bool {
	if o == nil || IsNil(o.OauthClientSecretSet) {
		var ret bool
		return ret
	}
	return *o.OauthClientSecretSet
}

// GetOauthClientSecretSetOk returns a tuple with the OauthClientSecretSet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminIdentityProviderResponse) GetOauthClientSecretSetOk() (*bool, bool) {
	if o == nil || IsNil(o.OauthClientSecretSet) {
		return nil, false
	}
	return o.OauthClientSecretSet, true
}

// HasOauthClientSecretSet returns a boolean if a field has been set.
func (o *AdminIdentityProviderResponse) HasOauthClientSecretSet() bool {
	if o != nil && !IsNil(o.OauthClientSecretSet) {
		return true
	}

	return false
}

// SetOauthClientSecretSet gets a reference to the given bool and assigns it to the OauthClientSecretSet field.
func (o *AdminIdentityProviderResponse) SetOauthClientSecretSet(v bool) {
	o.OauthClientSecretSet = &v
}

// GetRedirectUri returns the RedirectUri field value if set, zero value otherwise.
func (o *AdminIdentityProviderResponse) GetRedirectUri() string {
	if o == nil || IsNil(o.RedirectUri) {
		var ret string
		return ret
	}
	return *o.RedirectUri
}

// GetRedirectUriOk returns a tuple with the RedirectUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminIdentityProviderResponse) GetRedirectUriOk() (*string, bool) {
	if o == nil || IsNil(o.RedirectUri) {
		return nil, false
	}
	return o.RedirectUri, true
}

// HasRedirectUri returns a boolean if a field has been set.
func (o *AdminIdentityProviderResponse) HasRedirectUri() bool {
	if o != nil && !IsNil(o.RedirectUri) {
		return true
	}

	return false
}

// SetRedirectUri gets a reference to the given string and assigns it to the RedirectUri field.
func (o *AdminIdentityProviderResponse) SetRedirectUri(v string) {
	o.RedirectUri = &v
}

// GetSetupConsoleUrl returns the SetupConsoleUrl field value if set, zero value otherwise.
func (o *AdminIdentityProviderResponse) GetSetupConsoleUrl() string {
	if o == nil || IsNil(o.SetupConsoleUrl) {
		var ret string
		return ret
	}
	return *o.SetupConsoleUrl
}

// GetSetupConsoleUrlOk returns a tuple with the SetupConsoleUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminIdentityProviderResponse) GetSetupConsoleUrlOk() (*string, bool) {
	if o == nil || IsNil(o.SetupConsoleUrl) {
		return nil, false
	}
	return o.SetupConsoleUrl, true
}

// HasSetupConsoleUrl returns a boolean if a field has been set.
func (o *AdminIdentityProviderResponse) HasSetupConsoleUrl() bool {
	if o != nil && !IsNil(o.SetupConsoleUrl) {
		return true
	}

	return false
}

// SetSetupConsoleUrl gets a reference to the given string and assigns it to the SetupConsoleUrl field.
func (o *AdminIdentityProviderResponse) SetSetupConsoleUrl(v string) {
	o.SetupConsoleUrl = &v
}

func (o AdminIdentityProviderResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminIdentityProviderResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenant_id"] = o.TenantId
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Configured) {
		toSerialize["configured"] = o.Configured
	}
	if !IsNil(o.OauthClientId) {
		toSerialize["oauth_client_id"] = o.OauthClientId
	}
	if !IsNil(o.OauthClientSecretSet) {
		toSerialize["oauth_client_secret_set"] = o.OauthClientSecretSet
	}
	if !IsNil(o.RedirectUri) {
		toSerialize["redirect_uri"] = o.RedirectUri
	}
	if !IsNil(o.SetupConsoleUrl) {
		toSerialize["setup_console_url"] = o.SetupConsoleUrl
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AdminIdentityProviderResponse) UnmarshalJSON(data []byte) (err error) {
	varAdminIdentityProviderResponse := _AdminIdentityProviderResponse{}

	err = json.Unmarshal(data, &varAdminIdentityProviderResponse)

	if err != nil {
		return err
	}

	*o = AdminIdentityProviderResponse(varAdminIdentityProviderResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tenant_id")
		delete(additionalProperties, "provider")
		delete(additionalProperties, "name")
		delete(additionalProperties, "enabled")
		delete(additionalProperties, "configured")
		delete(additionalProperties, "oauth_client_id")
		delete(additionalProperties, "oauth_client_secret_set")
		delete(additionalProperties, "redirect_uri")
		delete(additionalProperties, "setup_console_url")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAdminIdentityProviderResponse struct {
	value *AdminIdentityProviderResponse
	isSet bool
}

func (v NullableAdminIdentityProviderResponse) Get() *AdminIdentityProviderResponse {
	return v.value
}

func (v *NullableAdminIdentityProviderResponse) Set(val *AdminIdentityProviderResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminIdentityProviderResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminIdentityProviderResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminIdentityProviderResponse(val *AdminIdentityProviderResponse) *NullableAdminIdentityProviderResponse {
	return &NullableAdminIdentityProviderResponse{value: val, isSet: true}
}

func (v NullableAdminIdentityProviderResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminIdentityProviderResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


