/*
GateForge IAM API

Public HTTP API for GateForge IAM — OpenID Connect / OAuth2 endpoints at the server root, plus the application JSON API under `/api/v1` (auth, MFA, WebAuthn, tenants, and platform admin). Success responses for `/api/v1` use a `{meta, data}` envelope. OAuth token and userinfo errors use `{error, error_description}`.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the MetaOnlyEnvelope type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MetaOnlyEnvelope{}

// MetaOnlyEnvelope struct for MetaOnlyEnvelope
type MetaOnlyEnvelope struct {
	Meta Meta `json:"meta"`
	AdditionalProperties map[string]interface{}
}

type _MetaOnlyEnvelope MetaOnlyEnvelope

// NewMetaOnlyEnvelope instantiates a new MetaOnlyEnvelope object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetaOnlyEnvelope(meta Meta) *MetaOnlyEnvelope {
	this := MetaOnlyEnvelope{}
	this.Meta = meta
	return &this
}

// NewMetaOnlyEnvelopeWithDefaults instantiates a new MetaOnlyEnvelope object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetaOnlyEnvelopeWithDefaults() *MetaOnlyEnvelope {
	this := MetaOnlyEnvelope{}
	return &this
}

// GetMeta returns the Meta field value
func (o *MetaOnlyEnvelope) GetMeta() Meta {
	if o == nil {
		var ret Meta
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *MetaOnlyEnvelope) GetMetaOk() (*Meta, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Meta, true
}

// SetMeta sets field value
func (o *MetaOnlyEnvelope) SetMeta(v Meta) {
	o.Meta = v
}

func (o MetaOnlyEnvelope) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MetaOnlyEnvelope) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["meta"] = o.Meta

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MetaOnlyEnvelope) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"meta",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMetaOnlyEnvelope := _MetaOnlyEnvelope{}

	err = json.Unmarshal(data, &varMetaOnlyEnvelope)

	if err != nil {
		return err
	}

	*o = MetaOnlyEnvelope(varMetaOnlyEnvelope)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "meta")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMetaOnlyEnvelope struct {
	value *MetaOnlyEnvelope
	isSet bool
}

func (v NullableMetaOnlyEnvelope) Get() *MetaOnlyEnvelope {
	return v.value
}

func (v *NullableMetaOnlyEnvelope) Set(val *MetaOnlyEnvelope) {
	v.value = val
	v.isSet = true
}

func (v NullableMetaOnlyEnvelope) IsSet() bool {
	return v.isSet
}

func (v *NullableMetaOnlyEnvelope) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetaOnlyEnvelope(val *MetaOnlyEnvelope) *NullableMetaOnlyEnvelope {
	return &NullableMetaOnlyEnvelope{value: val, isSet: true}
}

func (v NullableMetaOnlyEnvelope) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetaOnlyEnvelope) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


