/*
GateForge IAM API

Public HTTP API for GateForge IAM — OpenID Connect / OAuth2 endpoints at the server root, plus the application JSON API under `/api/v1` (auth, MFA, WebAuthn, tenants, and platform admin). Success responses for `/api/v1` use a `{meta, data}` envelope. OAuth token and userinfo errors use `{error, error_description}`.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the TokenIntrospectionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenIntrospectionRequest{}

// TokenIntrospectionRequest struct for TokenIntrospectionRequest
type TokenIntrospectionRequest struct {
	// The access or refresh token to introspect
	Token string `json:"token"`
	// Optional hint — access_token or refresh_token
	TokenTypeHint *string `json:"token_type_hint,omitempty"`
	// Confidential client id (when not using HTTP Basic)
	ClientId *string `json:"client_id,omitempty"`
	// Confidential client secret (when not using HTTP Basic)
	ClientSecret *string `json:"client_secret,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TokenIntrospectionRequest TokenIntrospectionRequest

// NewTokenIntrospectionRequest instantiates a new TokenIntrospectionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenIntrospectionRequest(token string) *TokenIntrospectionRequest {
	this := TokenIntrospectionRequest{}
	this.Token = token
	return &this
}

// NewTokenIntrospectionRequestWithDefaults instantiates a new TokenIntrospectionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenIntrospectionRequestWithDefaults() *TokenIntrospectionRequest {
	this := TokenIntrospectionRequest{}
	return &this
}

// GetToken returns the Token field value
func (o *TokenIntrospectionRequest) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *TokenIntrospectionRequest) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *TokenIntrospectionRequest) SetToken(v string) {
	o.Token = v
}

// GetTokenTypeHint returns the TokenTypeHint field value if set, zero value otherwise.
func (o *TokenIntrospectionRequest) GetTokenTypeHint() string {
	if o == nil || IsNil(o.TokenTypeHint) {
		var ret string
		return ret
	}
	return *o.TokenTypeHint
}

// GetTokenTypeHintOk returns a tuple with the TokenTypeHint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenIntrospectionRequest) GetTokenTypeHintOk() (*string, bool) {
	if o == nil || IsNil(o.TokenTypeHint) {
		return nil, false
	}
	return o.TokenTypeHint, true
}

// HasTokenTypeHint returns a boolean if a field has been set.
func (o *TokenIntrospectionRequest) HasTokenTypeHint() bool {
	if o != nil && !IsNil(o.TokenTypeHint) {
		return true
	}

	return false
}

// SetTokenTypeHint gets a reference to the given string and assigns it to the TokenTypeHint field.
func (o *TokenIntrospectionRequest) SetTokenTypeHint(v string) {
	o.TokenTypeHint = &v
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *TokenIntrospectionRequest) GetClientId() string {
	if o == nil || IsNil(o.ClientId) {
		var ret string
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenIntrospectionRequest) GetClientIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClientId) {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *TokenIntrospectionRequest) HasClientId() bool {
	if o != nil && !IsNil(o.ClientId) {
		return true
	}

	return false
}

// SetClientId gets a reference to the given string and assigns it to the ClientId field.
func (o *TokenIntrospectionRequest) SetClientId(v string) {
	o.ClientId = &v
}

// GetClientSecret returns the ClientSecret field value if set, zero value otherwise.
func (o *TokenIntrospectionRequest) GetClientSecret() string {
	if o == nil || IsNil(o.ClientSecret) {
		var ret string
		return ret
	}
	return *o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenIntrospectionRequest) GetClientSecretOk() (*string, bool) {
	if o == nil || IsNil(o.ClientSecret) {
		return nil, false
	}
	return o.ClientSecret, true
}

// HasClientSecret returns a boolean if a field has been set.
func (o *TokenIntrospectionRequest) HasClientSecret() bool {
	if o != nil && !IsNil(o.ClientSecret) {
		return true
	}

	return false
}

// SetClientSecret gets a reference to the given string and assigns it to the ClientSecret field.
func (o *TokenIntrospectionRequest) SetClientSecret(v string) {
	o.ClientSecret = &v
}

func (o TokenIntrospectionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenIntrospectionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["token"] = o.Token
	if !IsNil(o.TokenTypeHint) {
		toSerialize["token_type_hint"] = o.TokenTypeHint
	}
	if !IsNil(o.ClientId) {
		toSerialize["client_id"] = o.ClientId
	}
	if !IsNil(o.ClientSecret) {
		toSerialize["client_secret"] = o.ClientSecret
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TokenIntrospectionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTokenIntrospectionRequest := _TokenIntrospectionRequest{}

	err = json.Unmarshal(data, &varTokenIntrospectionRequest)

	if err != nil {
		return err
	}

	*o = TokenIntrospectionRequest(varTokenIntrospectionRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "token")
		delete(additionalProperties, "token_type_hint")
		delete(additionalProperties, "client_id")
		delete(additionalProperties, "client_secret")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTokenIntrospectionRequest struct {
	value *TokenIntrospectionRequest
	isSet bool
}

func (v NullableTokenIntrospectionRequest) Get() *TokenIntrospectionRequest {
	return v.value
}

func (v *NullableTokenIntrospectionRequest) Set(val *TokenIntrospectionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenIntrospectionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenIntrospectionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenIntrospectionRequest(val *TokenIntrospectionRequest) *NullableTokenIntrospectionRequest {
	return &NullableTokenIntrospectionRequest{value: val, isSet: true}
}

func (v NullableTokenIntrospectionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenIntrospectionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


