/*
GateForge IAM API

Public HTTP API for GateForge IAM — OpenID Connect / OAuth2 endpoints at the server root, plus the application JSON API under `/api/v1` (auth, MFA, WebAuthn, tenants, and platform admin). Success responses for `/api/v1` use a `{meta, data}` envelope. OAuth token and userinfo errors use `{error, error_description}`.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the AdminCreateClientResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminCreateClientResponse{}

// AdminCreateClientResponse struct for AdminCreateClientResponse
type AdminCreateClientResponse struct {
	Id *string `json:"id,omitempty"`
	ClientId *string `json:"client_id,omitempty"`
	ClientSecret *string `json:"client_secret,omitempty"`
	ClientSecretSet *bool `json:"client_secret_set,omitempty"`
	Name *string `json:"name,omitempty"`
	TenantId *string `json:"tenant_id,omitempty"`
	IsPublic *bool `json:"is_public,omitempty"`
	RedirectUris []string `json:"redirect_uris,omitempty"`
	GrantTypes []string `json:"grant_types,omitempty"`
	Scopes []string `json:"scopes,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AdminCreateClientResponse AdminCreateClientResponse

// NewAdminCreateClientResponse instantiates a new AdminCreateClientResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminCreateClientResponse() *AdminCreateClientResponse {
	this := AdminCreateClientResponse{}
	return &this
}

// NewAdminCreateClientResponseWithDefaults instantiates a new AdminCreateClientResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminCreateClientResponseWithDefaults() *AdminCreateClientResponse {
	this := AdminCreateClientResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AdminCreateClientResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminCreateClientResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AdminCreateClientResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *AdminCreateClientResponse) SetId(v string) {
	o.Id = &v
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *AdminCreateClientResponse) GetClientId() string {
	if o == nil || IsNil(o.ClientId) {
		var ret string
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminCreateClientResponse) GetClientIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClientId) {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *AdminCreateClientResponse) HasClientId() bool {
	if o != nil && !IsNil(o.ClientId) {
		return true
	}

	return false
}

// SetClientId gets a reference to the given string and assigns it to the ClientId field.
func (o *AdminCreateClientResponse) SetClientId(v string) {
	o.ClientId = &v
}

// GetClientSecret returns the ClientSecret field value if set, zero value otherwise.
func (o *AdminCreateClientResponse) GetClientSecret() string {
	if o == nil || IsNil(o.ClientSecret) {
		var ret string
		return ret
	}
	return *o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminCreateClientResponse) GetClientSecretOk() (*string, bool) {
	if o == nil || IsNil(o.ClientSecret) {
		return nil, false
	}
	return o.ClientSecret, true
}

// HasClientSecret returns a boolean if a field has been set.
func (o *AdminCreateClientResponse) HasClientSecret() bool {
	if o != nil && !IsNil(o.ClientSecret) {
		return true
	}

	return false
}

// SetClientSecret gets a reference to the given string and assigns it to the ClientSecret field.
func (o *AdminCreateClientResponse) SetClientSecret(v string) {
	o.ClientSecret = &v
}

// GetClientSecretSet returns the ClientSecretSet field value if set, zero value otherwise.
func (o *AdminCreateClientResponse) GetClientSecretSet() bool {
	if o == nil || IsNil(o.ClientSecretSet) {
		var ret bool
		return ret
	}
	return *o.ClientSecretSet
}

// GetClientSecretSetOk returns a tuple with the ClientSecretSet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminCreateClientResponse) GetClientSecretSetOk() (*bool, bool) {
	if o == nil || IsNil(o.ClientSecretSet) {
		return nil, false
	}
	return o.ClientSecretSet, true
}

// HasClientSecretSet returns a boolean if a field has been set.
func (o *AdminCreateClientResponse) HasClientSecretSet() bool {
	if o != nil && !IsNil(o.ClientSecretSet) {
		return true
	}

	return false
}

// SetClientSecretSet gets a reference to the given bool and assigns it to the ClientSecretSet field.
func (o *AdminCreateClientResponse) SetClientSecretSet(v bool) {
	o.ClientSecretSet = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AdminCreateClientResponse) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminCreateClientResponse) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AdminCreateClientResponse) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AdminCreateClientResponse) SetName(v string) {
	o.Name = &v
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *AdminCreateClientResponse) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminCreateClientResponse) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *AdminCreateClientResponse) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *AdminCreateClientResponse) SetTenantId(v string) {
	o.TenantId = &v
}

// GetIsPublic returns the IsPublic field value if set, zero value otherwise.
func (o *AdminCreateClientResponse) GetIsPublic() bool {
	if o == nil || IsNil(o.IsPublic) {
		var ret bool
		return ret
	}
	return *o.IsPublic
}

// GetIsPublicOk returns a tuple with the IsPublic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminCreateClientResponse) GetIsPublicOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPublic) {
		return nil, false
	}
	return o.IsPublic, true
}

// HasIsPublic returns a boolean if a field has been set.
func (o *AdminCreateClientResponse) HasIsPublic() bool {
	if o != nil && !IsNil(o.IsPublic) {
		return true
	}

	return false
}

// SetIsPublic gets a reference to the given bool and assigns it to the IsPublic field.
func (o *AdminCreateClientResponse) SetIsPublic(v bool) {
	o.IsPublic = &v
}

// GetRedirectUris returns the RedirectUris field value if set, zero value otherwise.
func (o *AdminCreateClientResponse) GetRedirectUris() []string {
	if o == nil || IsNil(o.RedirectUris) {
		var ret []string
		return ret
	}
	return o.RedirectUris
}

// GetRedirectUrisOk returns a tuple with the RedirectUris field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminCreateClientResponse) GetRedirectUrisOk() ([]string, bool) {
	if o == nil || IsNil(o.RedirectUris) {
		return nil, false
	}
	return o.RedirectUris, true
}

// HasRedirectUris returns a boolean if a field has been set.
func (o *AdminCreateClientResponse) HasRedirectUris() bool {
	if o != nil && !IsNil(o.RedirectUris) {
		return true
	}

	return false
}

// SetRedirectUris gets a reference to the given []string and assigns it to the RedirectUris field.
func (o *AdminCreateClientResponse) SetRedirectUris(v []string) {
	o.RedirectUris = v
}

// GetGrantTypes returns the GrantTypes field value if set, zero value otherwise.
func (o *AdminCreateClientResponse) GetGrantTypes() []string {
	if o == nil || IsNil(o.GrantTypes) {
		var ret []string
		return ret
	}
	return o.GrantTypes
}

// GetGrantTypesOk returns a tuple with the GrantTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminCreateClientResponse) GetGrantTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.GrantTypes) {
		return nil, false
	}
	return o.GrantTypes, true
}

// HasGrantTypes returns a boolean if a field has been set.
func (o *AdminCreateClientResponse) HasGrantTypes() bool {
	if o != nil && !IsNil(o.GrantTypes) {
		return true
	}

	return false
}

// SetGrantTypes gets a reference to the given []string and assigns it to the GrantTypes field.
func (o *AdminCreateClientResponse) SetGrantTypes(v []string) {
	o.GrantTypes = v
}

// GetScopes returns the Scopes field value if set, zero value otherwise.
func (o *AdminCreateClientResponse) GetScopes() []string {
	if o == nil || IsNil(o.Scopes) {
		var ret []string
		return ret
	}
	return o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminCreateClientResponse) GetScopesOk() ([]string, bool) {
	if o == nil || IsNil(o.Scopes) {
		return nil, false
	}
	return o.Scopes, true
}

// HasScopes returns a boolean if a field has been set.
func (o *AdminCreateClientResponse) HasScopes() bool {
	if o != nil && !IsNil(o.Scopes) {
		return true
	}

	return false
}

// SetScopes gets a reference to the given []string and assigns it to the Scopes field.
func (o *AdminCreateClientResponse) SetScopes(v []string) {
	o.Scopes = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *AdminCreateClientResponse) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminCreateClientResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *AdminCreateClientResponse) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *AdminCreateClientResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

func (o AdminCreateClientResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminCreateClientResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.ClientId) {
		toSerialize["client_id"] = o.ClientId
	}
	if !IsNil(o.ClientSecret) {
		toSerialize["client_secret"] = o.ClientSecret
	}
	if !IsNil(o.ClientSecretSet) {
		toSerialize["client_secret_set"] = o.ClientSecretSet
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.TenantId) {
		toSerialize["tenant_id"] = o.TenantId
	}
	if !IsNil(o.IsPublic) {
		toSerialize["is_public"] = o.IsPublic
	}
	if !IsNil(o.RedirectUris) {
		toSerialize["redirect_uris"] = o.RedirectUris
	}
	if !IsNil(o.GrantTypes) {
		toSerialize["grant_types"] = o.GrantTypes
	}
	if !IsNil(o.Scopes) {
		toSerialize["scopes"] = o.Scopes
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AdminCreateClientResponse) UnmarshalJSON(data []byte) (err error) {
	varAdminCreateClientResponse := _AdminCreateClientResponse{}

	err = json.Unmarshal(data, &varAdminCreateClientResponse)

	if err != nil {
		return err
	}

	*o = AdminCreateClientResponse(varAdminCreateClientResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "client_id")
		delete(additionalProperties, "client_secret")
		delete(additionalProperties, "client_secret_set")
		delete(additionalProperties, "name")
		delete(additionalProperties, "tenant_id")
		delete(additionalProperties, "is_public")
		delete(additionalProperties, "redirect_uris")
		delete(additionalProperties, "grant_types")
		delete(additionalProperties, "scopes")
		delete(additionalProperties, "created_at")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAdminCreateClientResponse struct {
	value *AdminCreateClientResponse
	isSet bool
}

func (v NullableAdminCreateClientResponse) Get() *AdminCreateClientResponse {
	return v.value
}

func (v *NullableAdminCreateClientResponse) Set(val *AdminCreateClientResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminCreateClientResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminCreateClientResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminCreateClientResponse(val *AdminCreateClientResponse) *NullableAdminCreateClientResponse {
	return &NullableAdminCreateClientResponse{value: val, isSet: true}
}

func (v NullableAdminCreateClientResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminCreateClientResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


