/*
GateForge IAM API

Public HTTP API for GateForge IAM — OpenID Connect / OAuth2 endpoints at the server root, plus the application JSON API under `/api/v1` (auth, MFA, WebAuthn, tenants, and platform admin). Success responses for `/api/v1` use a `{meta, data}` envelope. OAuth token and userinfo errors use `{error, error_description}`.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PatchIdentityProviderRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchIdentityProviderRequest{}

// PatchIdentityProviderRequest struct for PatchIdentityProviderRequest
type PatchIdentityProviderRequest struct {
	Enabled *bool `json:"enabled,omitempty"`
	OauthClientId *string `json:"oauth_client_id,omitempty"`
	OauthClientSecret *string `json:"oauth_client_secret,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PatchIdentityProviderRequest PatchIdentityProviderRequest

// NewPatchIdentityProviderRequest instantiates a new PatchIdentityProviderRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchIdentityProviderRequest() *PatchIdentityProviderRequest {
	this := PatchIdentityProviderRequest{}
	return &this
}

// NewPatchIdentityProviderRequestWithDefaults instantiates a new PatchIdentityProviderRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchIdentityProviderRequestWithDefaults() *PatchIdentityProviderRequest {
	this := PatchIdentityProviderRequest{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *PatchIdentityProviderRequest) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchIdentityProviderRequest) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *PatchIdentityProviderRequest) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *PatchIdentityProviderRequest) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetOauthClientId returns the OauthClientId field value if set, zero value otherwise.
func (o *PatchIdentityProviderRequest) GetOauthClientId() string {
	if o == nil || IsNil(o.OauthClientId) {
		var ret string
		return ret
	}
	return *o.OauthClientId
}

// GetOauthClientIdOk returns a tuple with the OauthClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchIdentityProviderRequest) GetOauthClientIdOk() (*string, bool) {
	if o == nil || IsNil(o.OauthClientId) {
		return nil, false
	}
	return o.OauthClientId, true
}

// HasOauthClientId returns a boolean if a field has been set.
func (o *PatchIdentityProviderRequest) HasOauthClientId() bool {
	if o != nil && !IsNil(o.OauthClientId) {
		return true
	}

	return false
}

// SetOauthClientId gets a reference to the given string and assigns it to the OauthClientId field.
func (o *PatchIdentityProviderRequest) SetOauthClientId(v string) {
	o.OauthClientId = &v
}

// GetOauthClientSecret returns the OauthClientSecret field value if set, zero value otherwise.
func (o *PatchIdentityProviderRequest) GetOauthClientSecret() string {
	if o == nil || IsNil(o.OauthClientSecret) {
		var ret string
		return ret
	}
	return *o.OauthClientSecret
}

// GetOauthClientSecretOk returns a tuple with the OauthClientSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchIdentityProviderRequest) GetOauthClientSecretOk() (*string, bool) {
	if o == nil || IsNil(o.OauthClientSecret) {
		return nil, false
	}
	return o.OauthClientSecret, true
}

// HasOauthClientSecret returns a boolean if a field has been set.
func (o *PatchIdentityProviderRequest) HasOauthClientSecret() bool {
	if o != nil && !IsNil(o.OauthClientSecret) {
		return true
	}

	return false
}

// SetOauthClientSecret gets a reference to the given string and assigns it to the OauthClientSecret field.
func (o *PatchIdentityProviderRequest) SetOauthClientSecret(v string) {
	o.OauthClientSecret = &v
}

func (o PatchIdentityProviderRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchIdentityProviderRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.OauthClientId) {
		toSerialize["oauth_client_id"] = o.OauthClientId
	}
	if !IsNil(o.OauthClientSecret) {
		toSerialize["oauth_client_secret"] = o.OauthClientSecret
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PatchIdentityProviderRequest) UnmarshalJSON(data []byte) (err error) {
	varPatchIdentityProviderRequest := _PatchIdentityProviderRequest{}

	err = json.Unmarshal(data, &varPatchIdentityProviderRequest)

	if err != nil {
		return err
	}

	*o = PatchIdentityProviderRequest(varPatchIdentityProviderRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "enabled")
		delete(additionalProperties, "oauth_client_id")
		delete(additionalProperties, "oauth_client_secret")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePatchIdentityProviderRequest struct {
	value *PatchIdentityProviderRequest
	isSet bool
}

func (v NullablePatchIdentityProviderRequest) Get() *PatchIdentityProviderRequest {
	return v.value
}

func (v *NullablePatchIdentityProviderRequest) Set(val *PatchIdentityProviderRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchIdentityProviderRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchIdentityProviderRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchIdentityProviderRequest(val *PatchIdentityProviderRequest) *NullablePatchIdentityProviderRequest {
	return &NullablePatchIdentityProviderRequest{value: val, isSet: true}
}

func (v NullablePatchIdentityProviderRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchIdentityProviderRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


