/*
GateForge IAM API

Public HTTP API for GateForge IAM — OpenID Connect / OAuth2 endpoints at the server root, plus the application JSON API under `/api/v1` (auth, MFA, WebAuthn, tenants, and platform admin). Success responses for `/api/v1` use a `{meta, data}` envelope. OAuth token and userinfo errors use `{error, error_description}`.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the WebauthnRegisterStartResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebauthnRegisterStartResponse{}

// WebauthnRegisterStartResponse struct for WebauthnRegisterStartResponse
type WebauthnRegisterStartResponse struct {
	Options map[string]interface{} `json:"options,omitempty"`
	SessionToken *string `json:"session_token,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _WebauthnRegisterStartResponse WebauthnRegisterStartResponse

// NewWebauthnRegisterStartResponse instantiates a new WebauthnRegisterStartResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebauthnRegisterStartResponse() *WebauthnRegisterStartResponse {
	this := WebauthnRegisterStartResponse{}
	return &this
}

// NewWebauthnRegisterStartResponseWithDefaults instantiates a new WebauthnRegisterStartResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebauthnRegisterStartResponseWithDefaults() *WebauthnRegisterStartResponse {
	this := WebauthnRegisterStartResponse{}
	return &this
}

// GetOptions returns the Options field value if set, zero value otherwise.
func (o *WebauthnRegisterStartResponse) GetOptions() map[string]interface{} {
	if o == nil || IsNil(o.Options) {
		var ret map[string]interface{}
		return ret
	}
	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebauthnRegisterStartResponse) GetOptionsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Options) {
		return map[string]interface{}{}, false
	}
	return o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *WebauthnRegisterStartResponse) HasOptions() bool {
	if o != nil && !IsNil(o.Options) {
		return true
	}

	return false
}

// SetOptions gets a reference to the given map[string]interface{} and assigns it to the Options field.
func (o *WebauthnRegisterStartResponse) SetOptions(v map[string]interface{}) {
	o.Options = v
}

// GetSessionToken returns the SessionToken field value if set, zero value otherwise.
func (o *WebauthnRegisterStartResponse) GetSessionToken() string {
	if o == nil || IsNil(o.SessionToken) {
		var ret string
		return ret
	}
	return *o.SessionToken
}

// GetSessionTokenOk returns a tuple with the SessionToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebauthnRegisterStartResponse) GetSessionTokenOk() (*string, bool) {
	if o == nil || IsNil(o.SessionToken) {
		return nil, false
	}
	return o.SessionToken, true
}

// HasSessionToken returns a boolean if a field has been set.
func (o *WebauthnRegisterStartResponse) HasSessionToken() bool {
	if o != nil && !IsNil(o.SessionToken) {
		return true
	}

	return false
}

// SetSessionToken gets a reference to the given string and assigns it to the SessionToken field.
func (o *WebauthnRegisterStartResponse) SetSessionToken(v string) {
	o.SessionToken = &v
}

func (o WebauthnRegisterStartResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebauthnRegisterStartResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Options) {
		toSerialize["options"] = o.Options
	}
	if !IsNil(o.SessionToken) {
		toSerialize["session_token"] = o.SessionToken
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WebauthnRegisterStartResponse) UnmarshalJSON(data []byte) (err error) {
	varWebauthnRegisterStartResponse := _WebauthnRegisterStartResponse{}

	err = json.Unmarshal(data, &varWebauthnRegisterStartResponse)

	if err != nil {
		return err
	}

	*o = WebauthnRegisterStartResponse(varWebauthnRegisterStartResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "options")
		delete(additionalProperties, "session_token")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWebauthnRegisterStartResponse struct {
	value *WebauthnRegisterStartResponse
	isSet bool
}

func (v NullableWebauthnRegisterStartResponse) Get() *WebauthnRegisterStartResponse {
	return v.value
}

func (v *NullableWebauthnRegisterStartResponse) Set(val *WebauthnRegisterStartResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWebauthnRegisterStartResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWebauthnRegisterStartResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebauthnRegisterStartResponse(val *WebauthnRegisterStartResponse) *NullableWebauthnRegisterStartResponse {
	return &NullableWebauthnRegisterStartResponse{value: val, isSet: true}
}

func (v NullableWebauthnRegisterStartResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebauthnRegisterStartResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


