/*
GateForge IAM API

Public HTTP API for GateForge IAM — OpenID Connect / OAuth2 endpoints at the server root, plus the application JSON API under `/api/v1` (auth, MFA, WebAuthn, tenants, and platform admin). Success responses for `/api/v1` use a `{meta, data}` envelope. OAuth token and userinfo errors use `{error, error_description}`.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the WebauthnRegisterStartRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebauthnRegisterStartRequest{}

// WebauthnRegisterStartRequest struct for WebauthnRegisterStartRequest
type WebauthnRegisterStartRequest struct {
	// Optional label stored with the passkey
	DeviceName *string `json:"device_name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _WebauthnRegisterStartRequest WebauthnRegisterStartRequest

// NewWebauthnRegisterStartRequest instantiates a new WebauthnRegisterStartRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebauthnRegisterStartRequest() *WebauthnRegisterStartRequest {
	this := WebauthnRegisterStartRequest{}
	return &this
}

// NewWebauthnRegisterStartRequestWithDefaults instantiates a new WebauthnRegisterStartRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebauthnRegisterStartRequestWithDefaults() *WebauthnRegisterStartRequest {
	this := WebauthnRegisterStartRequest{}
	return &this
}

// GetDeviceName returns the DeviceName field value if set, zero value otherwise.
func (o *WebauthnRegisterStartRequest) GetDeviceName() string {
	if o == nil || IsNil(o.DeviceName) {
		var ret string
		return ret
	}
	return *o.DeviceName
}

// GetDeviceNameOk returns a tuple with the DeviceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebauthnRegisterStartRequest) GetDeviceNameOk() (*string, bool) {
	if o == nil || IsNil(o.DeviceName) {
		return nil, false
	}
	return o.DeviceName, true
}

// HasDeviceName returns a boolean if a field has been set.
func (o *WebauthnRegisterStartRequest) HasDeviceName() bool {
	if o != nil && !IsNil(o.DeviceName) {
		return true
	}

	return false
}

// SetDeviceName gets a reference to the given string and assigns it to the DeviceName field.
func (o *WebauthnRegisterStartRequest) SetDeviceName(v string) {
	o.DeviceName = &v
}

func (o WebauthnRegisterStartRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebauthnRegisterStartRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeviceName) {
		toSerialize["device_name"] = o.DeviceName
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WebauthnRegisterStartRequest) UnmarshalJSON(data []byte) (err error) {
	varWebauthnRegisterStartRequest := _WebauthnRegisterStartRequest{}

	err = json.Unmarshal(data, &varWebauthnRegisterStartRequest)

	if err != nil {
		return err
	}

	*o = WebauthnRegisterStartRequest(varWebauthnRegisterStartRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "device_name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWebauthnRegisterStartRequest struct {
	value *WebauthnRegisterStartRequest
	isSet bool
}

func (v NullableWebauthnRegisterStartRequest) Get() *WebauthnRegisterStartRequest {
	return v.value
}

func (v *NullableWebauthnRegisterStartRequest) Set(val *WebauthnRegisterStartRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWebauthnRegisterStartRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWebauthnRegisterStartRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebauthnRegisterStartRequest(val *WebauthnRegisterStartRequest) *NullableWebauthnRegisterStartRequest {
	return &NullableWebauthnRegisterStartRequest{value: val, isSet: true}
}

func (v NullableWebauthnRegisterStartRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebauthnRegisterStartRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


