/*
GateForge IAM API

Public HTTP API for GateForge IAM — OpenID Connect / OAuth2 endpoints at the server root, plus the application JSON API under `/api/v1` (auth, MFA, WebAuthn, tenants, and platform admin). Success responses for `/api/v1` use a `{meta, data}` envelope. OAuth token and userinfo errors use `{error, error_description}`.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the TenantSelectRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenantSelectRequest{}

// TenantSelectRequest struct for TenantSelectRequest
type TenantSelectRequest struct {
	SelectionToken string `json:"selection_token"`
	TenantId string `json:"tenant_id"`
	RememberMe *bool `json:"remember_me,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TenantSelectRequest TenantSelectRequest

// NewTenantSelectRequest instantiates a new TenantSelectRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantSelectRequest(selectionToken string, tenantId string) *TenantSelectRequest {
	this := TenantSelectRequest{}
	this.SelectionToken = selectionToken
	this.TenantId = tenantId
	return &this
}

// NewTenantSelectRequestWithDefaults instantiates a new TenantSelectRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantSelectRequestWithDefaults() *TenantSelectRequest {
	this := TenantSelectRequest{}
	return &this
}

// GetSelectionToken returns the SelectionToken field value
func (o *TenantSelectRequest) GetSelectionToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SelectionToken
}

// GetSelectionTokenOk returns a tuple with the SelectionToken field value
// and a boolean to check if the value has been set.
func (o *TenantSelectRequest) GetSelectionTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SelectionToken, true
}

// SetSelectionToken sets field value
func (o *TenantSelectRequest) SetSelectionToken(v string) {
	o.SelectionToken = v
}

// GetTenantId returns the TenantId field value
func (o *TenantSelectRequest) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *TenantSelectRequest) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *TenantSelectRequest) SetTenantId(v string) {
	o.TenantId = v
}

// GetRememberMe returns the RememberMe field value if set, zero value otherwise.
func (o *TenantSelectRequest) GetRememberMe() bool {
	if o == nil || IsNil(o.RememberMe) {
		var ret bool
		return ret
	}
	return *o.RememberMe
}

// GetRememberMeOk returns a tuple with the RememberMe field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantSelectRequest) GetRememberMeOk() (*bool, bool) {
	if o == nil || IsNil(o.RememberMe) {
		return nil, false
	}
	return o.RememberMe, true
}

// HasRememberMe returns a boolean if a field has been set.
func (o *TenantSelectRequest) HasRememberMe() bool {
	if o != nil && !IsNil(o.RememberMe) {
		return true
	}

	return false
}

// SetRememberMe gets a reference to the given bool and assigns it to the RememberMe field.
func (o *TenantSelectRequest) SetRememberMe(v bool) {
	o.RememberMe = &v
}

func (o TenantSelectRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenantSelectRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["selection_token"] = o.SelectionToken
	toSerialize["tenant_id"] = o.TenantId
	if !IsNil(o.RememberMe) {
		toSerialize["remember_me"] = o.RememberMe
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TenantSelectRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"selection_token",
		"tenant_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTenantSelectRequest := _TenantSelectRequest{}

	err = json.Unmarshal(data, &varTenantSelectRequest)

	if err != nil {
		return err
	}

	*o = TenantSelectRequest(varTenantSelectRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "selection_token")
		delete(additionalProperties, "tenant_id")
		delete(additionalProperties, "remember_me")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTenantSelectRequest struct {
	value *TenantSelectRequest
	isSet bool
}

func (v NullableTenantSelectRequest) Get() *TenantSelectRequest {
	return v.value
}

func (v *NullableTenantSelectRequest) Set(val *TenantSelectRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantSelectRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantSelectRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantSelectRequest(val *TenantSelectRequest) *NullableTenantSelectRequest {
	return &NullableTenantSelectRequest{value: val, isSet: true}
}

func (v NullableTenantSelectRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantSelectRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


