/*
GateForge IAM API

Public HTTP API for GateForge IAM — OpenID Connect / OAuth2 endpoints at the server root, plus the application JSON API under `/api/v1` (auth, MFA, WebAuthn, tenants, and platform admin). Success responses for `/api/v1` use a `{meta, data}` envelope. OAuth token and userinfo errors use `{error, error_description}`.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the WebauthnCredentialListEnvelope type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebauthnCredentialListEnvelope{}

// WebauthnCredentialListEnvelope struct for WebauthnCredentialListEnvelope
type WebauthnCredentialListEnvelope struct {
	Meta Meta `json:"meta"`
	Data []WebauthnCredentialResponse `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _WebauthnCredentialListEnvelope WebauthnCredentialListEnvelope

// NewWebauthnCredentialListEnvelope instantiates a new WebauthnCredentialListEnvelope object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebauthnCredentialListEnvelope(meta Meta, data []WebauthnCredentialResponse) *WebauthnCredentialListEnvelope {
	this := WebauthnCredentialListEnvelope{}
	this.Meta = meta
	this.Data = data
	return &this
}

// NewWebauthnCredentialListEnvelopeWithDefaults instantiates a new WebauthnCredentialListEnvelope object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebauthnCredentialListEnvelopeWithDefaults() *WebauthnCredentialListEnvelope {
	this := WebauthnCredentialListEnvelope{}
	return &this
}

// GetMeta returns the Meta field value
func (o *WebauthnCredentialListEnvelope) GetMeta() Meta {
	if o == nil {
		var ret Meta
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *WebauthnCredentialListEnvelope) GetMetaOk() (*Meta, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Meta, true
}

// SetMeta sets field value
func (o *WebauthnCredentialListEnvelope) SetMeta(v Meta) {
	o.Meta = v
}

// GetData returns the Data field value
func (o *WebauthnCredentialListEnvelope) GetData() []WebauthnCredentialResponse {
	if o == nil {
		var ret []WebauthnCredentialResponse
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *WebauthnCredentialListEnvelope) GetDataOk() ([]WebauthnCredentialResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *WebauthnCredentialListEnvelope) SetData(v []WebauthnCredentialResponse) {
	o.Data = v
}

func (o WebauthnCredentialListEnvelope) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebauthnCredentialListEnvelope) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["meta"] = o.Meta
	toSerialize["data"] = o.Data

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WebauthnCredentialListEnvelope) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"meta",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebauthnCredentialListEnvelope := _WebauthnCredentialListEnvelope{}

	err = json.Unmarshal(data, &varWebauthnCredentialListEnvelope)

	if err != nil {
		return err
	}

	*o = WebauthnCredentialListEnvelope(varWebauthnCredentialListEnvelope)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "meta")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWebauthnCredentialListEnvelope struct {
	value *WebauthnCredentialListEnvelope
	isSet bool
}

func (v NullableWebauthnCredentialListEnvelope) Get() *WebauthnCredentialListEnvelope {
	return v.value
}

func (v *NullableWebauthnCredentialListEnvelope) Set(val *WebauthnCredentialListEnvelope) {
	v.value = val
	v.isSet = true
}

func (v NullableWebauthnCredentialListEnvelope) IsSet() bool {
	return v.isSet
}

func (v *NullableWebauthnCredentialListEnvelope) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebauthnCredentialListEnvelope(val *WebauthnCredentialListEnvelope) *NullableWebauthnCredentialListEnvelope {
	return &NullableWebauthnCredentialListEnvelope{value: val, isSet: true}
}

func (v NullableWebauthnCredentialListEnvelope) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebauthnCredentialListEnvelope) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


