/*
GateForge IAM API

Public HTTP API for GateForge IAM — OpenID Connect / OAuth2 endpoints at the server root, plus the application JSON API under `/api/v1` (auth, MFA, WebAuthn, tenants, and platform admin). Success responses for `/api/v1` use a `{meta, data}` envelope. OAuth token and userinfo errors use `{error, error_description}`.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the LoginResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoginResponse{}

// LoginResponse struct for LoginResponse
type LoginResponse struct {
	AccessToken *string `json:"access_token,omitempty"`
	RefreshToken *string `json:"refresh_token,omitempty"`
	TokenType *string `json:"token_type,omitempty"`
	// Access token lifetime in seconds
	ExpiresIn *int32 `json:"expires_in,omitempty"`
	// Refresh token lifetime in seconds
	RefreshExpiresIn *int32 `json:"refresh_expires_in,omitempty"`
	ActiveTenantId *string `json:"active_tenant_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _LoginResponse LoginResponse

// NewLoginResponse instantiates a new LoginResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoginResponse() *LoginResponse {
	this := LoginResponse{}
	return &this
}

// NewLoginResponseWithDefaults instantiates a new LoginResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoginResponseWithDefaults() *LoginResponse {
	this := LoginResponse{}
	return &this
}

// GetAccessToken returns the AccessToken field value if set, zero value otherwise.
func (o *LoginResponse) GetAccessToken() string {
	if o == nil || IsNil(o.AccessToken) {
		var ret string
		return ret
	}
	return *o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoginResponse) GetAccessTokenOk() (*string, bool) {
	if o == nil || IsNil(o.AccessToken) {
		return nil, false
	}
	return o.AccessToken, true
}

// HasAccessToken returns a boolean if a field has been set.
func (o *LoginResponse) HasAccessToken() bool {
	if o != nil && !IsNil(o.AccessToken) {
		return true
	}

	return false
}

// SetAccessToken gets a reference to the given string and assigns it to the AccessToken field.
func (o *LoginResponse) SetAccessToken(v string) {
	o.AccessToken = &v
}

// GetRefreshToken returns the RefreshToken field value if set, zero value otherwise.
func (o *LoginResponse) GetRefreshToken() string {
	if o == nil || IsNil(o.RefreshToken) {
		var ret string
		return ret
	}
	return *o.RefreshToken
}

// GetRefreshTokenOk returns a tuple with the RefreshToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoginResponse) GetRefreshTokenOk() (*string, bool) {
	if o == nil || IsNil(o.RefreshToken) {
		return nil, false
	}
	return o.RefreshToken, true
}

// HasRefreshToken returns a boolean if a field has been set.
func (o *LoginResponse) HasRefreshToken() bool {
	if o != nil && !IsNil(o.RefreshToken) {
		return true
	}

	return false
}

// SetRefreshToken gets a reference to the given string and assigns it to the RefreshToken field.
func (o *LoginResponse) SetRefreshToken(v string) {
	o.RefreshToken = &v
}

// GetTokenType returns the TokenType field value if set, zero value otherwise.
func (o *LoginResponse) GetTokenType() string {
	if o == nil || IsNil(o.TokenType) {
		var ret string
		return ret
	}
	return *o.TokenType
}

// GetTokenTypeOk returns a tuple with the TokenType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoginResponse) GetTokenTypeOk() (*string, bool) {
	if o == nil || IsNil(o.TokenType) {
		return nil, false
	}
	return o.TokenType, true
}

// HasTokenType returns a boolean if a field has been set.
func (o *LoginResponse) HasTokenType() bool {
	if o != nil && !IsNil(o.TokenType) {
		return true
	}

	return false
}

// SetTokenType gets a reference to the given string and assigns it to the TokenType field.
func (o *LoginResponse) SetTokenType(v string) {
	o.TokenType = &v
}

// GetExpiresIn returns the ExpiresIn field value if set, zero value otherwise.
func (o *LoginResponse) GetExpiresIn() int32 {
	if o == nil || IsNil(o.ExpiresIn) {
		var ret int32
		return ret
	}
	return *o.ExpiresIn
}

// GetExpiresInOk returns a tuple with the ExpiresIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoginResponse) GetExpiresInOk() (*int32, bool) {
	if o == nil || IsNil(o.ExpiresIn) {
		return nil, false
	}
	return o.ExpiresIn, true
}

// HasExpiresIn returns a boolean if a field has been set.
func (o *LoginResponse) HasExpiresIn() bool {
	if o != nil && !IsNil(o.ExpiresIn) {
		return true
	}

	return false
}

// SetExpiresIn gets a reference to the given int32 and assigns it to the ExpiresIn field.
func (o *LoginResponse) SetExpiresIn(v int32) {
	o.ExpiresIn = &v
}

// GetRefreshExpiresIn returns the RefreshExpiresIn field value if set, zero value otherwise.
func (o *LoginResponse) GetRefreshExpiresIn() int32 {
	if o == nil || IsNil(o.RefreshExpiresIn) {
		var ret int32
		return ret
	}
	return *o.RefreshExpiresIn
}

// GetRefreshExpiresInOk returns a tuple with the RefreshExpiresIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoginResponse) GetRefreshExpiresInOk() (*int32, bool) {
	if o == nil || IsNil(o.RefreshExpiresIn) {
		return nil, false
	}
	return o.RefreshExpiresIn, true
}

// HasRefreshExpiresIn returns a boolean if a field has been set.
func (o *LoginResponse) HasRefreshExpiresIn() bool {
	if o != nil && !IsNil(o.RefreshExpiresIn) {
		return true
	}

	return false
}

// SetRefreshExpiresIn gets a reference to the given int32 and assigns it to the RefreshExpiresIn field.
func (o *LoginResponse) SetRefreshExpiresIn(v int32) {
	o.RefreshExpiresIn = &v
}

// GetActiveTenantId returns the ActiveTenantId field value if set, zero value otherwise.
func (o *LoginResponse) GetActiveTenantId() string {
	if o == nil || IsNil(o.ActiveTenantId) {
		var ret string
		return ret
	}
	return *o.ActiveTenantId
}

// GetActiveTenantIdOk returns a tuple with the ActiveTenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoginResponse) GetActiveTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.ActiveTenantId) {
		return nil, false
	}
	return o.ActiveTenantId, true
}

// HasActiveTenantId returns a boolean if a field has been set.
func (o *LoginResponse) HasActiveTenantId() bool {
	if o != nil && !IsNil(o.ActiveTenantId) {
		return true
	}

	return false
}

// SetActiveTenantId gets a reference to the given string and assigns it to the ActiveTenantId field.
func (o *LoginResponse) SetActiveTenantId(v string) {
	o.ActiveTenantId = &v
}

func (o LoginResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoginResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccessToken) {
		toSerialize["access_token"] = o.AccessToken
	}
	if !IsNil(o.RefreshToken) {
		toSerialize["refresh_token"] = o.RefreshToken
	}
	if !IsNil(o.TokenType) {
		toSerialize["token_type"] = o.TokenType
	}
	if !IsNil(o.ExpiresIn) {
		toSerialize["expires_in"] = o.ExpiresIn
	}
	if !IsNil(o.RefreshExpiresIn) {
		toSerialize["refresh_expires_in"] = o.RefreshExpiresIn
	}
	if !IsNil(o.ActiveTenantId) {
		toSerialize["active_tenant_id"] = o.ActiveTenantId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *LoginResponse) UnmarshalJSON(data []byte) (err error) {
	varLoginResponse := _LoginResponse{}

	err = json.Unmarshal(data, &varLoginResponse)

	if err != nil {
		return err
	}

	*o = LoginResponse(varLoginResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "access_token")
		delete(additionalProperties, "refresh_token")
		delete(additionalProperties, "token_type")
		delete(additionalProperties, "expires_in")
		delete(additionalProperties, "refresh_expires_in")
		delete(additionalProperties, "active_tenant_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableLoginResponse struct {
	value *LoginResponse
	isSet bool
}

func (v NullableLoginResponse) Get() *LoginResponse {
	return v.value
}

func (v *NullableLoginResponse) Set(val *LoginResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLoginResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLoginResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoginResponse(val *LoginResponse) *NullableLoginResponse {
	return &NullableLoginResponse{value: val, isSet: true}
}

func (v NullableLoginResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoginResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


