/*
GateForge IAM API

Public HTTP API for GateForge IAM — OpenID Connect / OAuth2 endpoints at the server root, plus the application JSON API under `/api/v1` (auth, MFA, WebAuthn, tenants, and platform admin). Success responses for `/api/v1` use a `{meta, data}` envelope. OAuth token and userinfo errors use `{error, error_description}`.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AdminUpdateClientRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminUpdateClientRequest{}

// AdminUpdateClientRequest struct for AdminUpdateClientRequest
type AdminUpdateClientRequest struct {
	Name *string `json:"name,omitempty"`
	ClientSecret *string `json:"client_secret,omitempty"`
	IsPublic *bool `json:"is_public,omitempty"`
	RedirectUris []string `json:"redirect_uris,omitempty"`
	GrantTypes []string `json:"grant_types,omitempty"`
	Scopes []string `json:"scopes,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AdminUpdateClientRequest AdminUpdateClientRequest

// NewAdminUpdateClientRequest instantiates a new AdminUpdateClientRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminUpdateClientRequest() *AdminUpdateClientRequest {
	this := AdminUpdateClientRequest{}
	return &this
}

// NewAdminUpdateClientRequestWithDefaults instantiates a new AdminUpdateClientRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminUpdateClientRequestWithDefaults() *AdminUpdateClientRequest {
	this := AdminUpdateClientRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AdminUpdateClientRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminUpdateClientRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AdminUpdateClientRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AdminUpdateClientRequest) SetName(v string) {
	o.Name = &v
}

// GetClientSecret returns the ClientSecret field value if set, zero value otherwise.
func (o *AdminUpdateClientRequest) GetClientSecret() string {
	if o == nil || IsNil(o.ClientSecret) {
		var ret string
		return ret
	}
	return *o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminUpdateClientRequest) GetClientSecretOk() (*string, bool) {
	if o == nil || IsNil(o.ClientSecret) {
		return nil, false
	}
	return o.ClientSecret, true
}

// HasClientSecret returns a boolean if a field has been set.
func (o *AdminUpdateClientRequest) HasClientSecret() bool {
	if o != nil && !IsNil(o.ClientSecret) {
		return true
	}

	return false
}

// SetClientSecret gets a reference to the given string and assigns it to the ClientSecret field.
func (o *AdminUpdateClientRequest) SetClientSecret(v string) {
	o.ClientSecret = &v
}

// GetIsPublic returns the IsPublic field value if set, zero value otherwise.
func (o *AdminUpdateClientRequest) GetIsPublic() bool {
	if o == nil || IsNil(o.IsPublic) {
		var ret bool
		return ret
	}
	return *o.IsPublic
}

// GetIsPublicOk returns a tuple with the IsPublic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminUpdateClientRequest) GetIsPublicOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPublic) {
		return nil, false
	}
	return o.IsPublic, true
}

// HasIsPublic returns a boolean if a field has been set.
func (o *AdminUpdateClientRequest) HasIsPublic() bool {
	if o != nil && !IsNil(o.IsPublic) {
		return true
	}

	return false
}

// SetIsPublic gets a reference to the given bool and assigns it to the IsPublic field.
func (o *AdminUpdateClientRequest) SetIsPublic(v bool) {
	o.IsPublic = &v
}

// GetRedirectUris returns the RedirectUris field value if set, zero value otherwise.
func (o *AdminUpdateClientRequest) GetRedirectUris() []string {
	if o == nil || IsNil(o.RedirectUris) {
		var ret []string
		return ret
	}
	return o.RedirectUris
}

// GetRedirectUrisOk returns a tuple with the RedirectUris field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminUpdateClientRequest) GetRedirectUrisOk() ([]string, bool) {
	if o == nil || IsNil(o.RedirectUris) {
		return nil, false
	}
	return o.RedirectUris, true
}

// HasRedirectUris returns a boolean if a field has been set.
func (o *AdminUpdateClientRequest) HasRedirectUris() bool {
	if o != nil && !IsNil(o.RedirectUris) {
		return true
	}

	return false
}

// SetRedirectUris gets a reference to the given []string and assigns it to the RedirectUris field.
func (o *AdminUpdateClientRequest) SetRedirectUris(v []string) {
	o.RedirectUris = v
}

// GetGrantTypes returns the GrantTypes field value if set, zero value otherwise.
func (o *AdminUpdateClientRequest) GetGrantTypes() []string {
	if o == nil || IsNil(o.GrantTypes) {
		var ret []string
		return ret
	}
	return o.GrantTypes
}

// GetGrantTypesOk returns a tuple with the GrantTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminUpdateClientRequest) GetGrantTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.GrantTypes) {
		return nil, false
	}
	return o.GrantTypes, true
}

// HasGrantTypes returns a boolean if a field has been set.
func (o *AdminUpdateClientRequest) HasGrantTypes() bool {
	if o != nil && !IsNil(o.GrantTypes) {
		return true
	}

	return false
}

// SetGrantTypes gets a reference to the given []string and assigns it to the GrantTypes field.
func (o *AdminUpdateClientRequest) SetGrantTypes(v []string) {
	o.GrantTypes = v
}

// GetScopes returns the Scopes field value if set, zero value otherwise.
func (o *AdminUpdateClientRequest) GetScopes() []string {
	if o == nil || IsNil(o.Scopes) {
		var ret []string
		return ret
	}
	return o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminUpdateClientRequest) GetScopesOk() ([]string, bool) {
	if o == nil || IsNil(o.Scopes) {
		return nil, false
	}
	return o.Scopes, true
}

// HasScopes returns a boolean if a field has been set.
func (o *AdminUpdateClientRequest) HasScopes() bool {
	if o != nil && !IsNil(o.Scopes) {
		return true
	}

	return false
}

// SetScopes gets a reference to the given []string and assigns it to the Scopes field.
func (o *AdminUpdateClientRequest) SetScopes(v []string) {
	o.Scopes = v
}

func (o AdminUpdateClientRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminUpdateClientRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ClientSecret) {
		toSerialize["client_secret"] = o.ClientSecret
	}
	if !IsNil(o.IsPublic) {
		toSerialize["is_public"] = o.IsPublic
	}
	if !IsNil(o.RedirectUris) {
		toSerialize["redirect_uris"] = o.RedirectUris
	}
	if !IsNil(o.GrantTypes) {
		toSerialize["grant_types"] = o.GrantTypes
	}
	if !IsNil(o.Scopes) {
		toSerialize["scopes"] = o.Scopes
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AdminUpdateClientRequest) UnmarshalJSON(data []byte) (err error) {
	varAdminUpdateClientRequest := _AdminUpdateClientRequest{}

	err = json.Unmarshal(data, &varAdminUpdateClientRequest)

	if err != nil {
		return err
	}

	*o = AdminUpdateClientRequest(varAdminUpdateClientRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "client_secret")
		delete(additionalProperties, "is_public")
		delete(additionalProperties, "redirect_uris")
		delete(additionalProperties, "grant_types")
		delete(additionalProperties, "scopes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAdminUpdateClientRequest struct {
	value *AdminUpdateClientRequest
	isSet bool
}

func (v NullableAdminUpdateClientRequest) Get() *AdminUpdateClientRequest {
	return v.value
}

func (v *NullableAdminUpdateClientRequest) Set(val *AdminUpdateClientRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminUpdateClientRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminUpdateClientRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminUpdateClientRequest(val *AdminUpdateClientRequest) *NullableAdminUpdateClientRequest {
	return &NullableAdminUpdateClientRequest{value: val, isSet: true}
}

func (v NullableAdminUpdateClientRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminUpdateClientRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


