/*
GateForge IAM API

Public HTTP API for GateForge IAM — OpenID Connect / OAuth2 endpoints at the server root, plus the application JSON API under `/api/v1` (auth, MFA, WebAuthn, tenants, and platform admin). Success responses for `/api/v1` use a `{meta, data}` envelope. OAuth token and userinfo errors use `{error, error_description}`.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the MFARecoveryCodesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MFARecoveryCodesResponse{}

// MFARecoveryCodesResponse struct for MFARecoveryCodesResponse
type MFARecoveryCodesResponse struct {
	Codes []string `json:"codes,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _MFARecoveryCodesResponse MFARecoveryCodesResponse

// NewMFARecoveryCodesResponse instantiates a new MFARecoveryCodesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMFARecoveryCodesResponse() *MFARecoveryCodesResponse {
	this := MFARecoveryCodesResponse{}
	return &this
}

// NewMFARecoveryCodesResponseWithDefaults instantiates a new MFARecoveryCodesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMFARecoveryCodesResponseWithDefaults() *MFARecoveryCodesResponse {
	this := MFARecoveryCodesResponse{}
	return &this
}

// GetCodes returns the Codes field value if set, zero value otherwise.
func (o *MFARecoveryCodesResponse) GetCodes() []string {
	if o == nil || IsNil(o.Codes) {
		var ret []string
		return ret
	}
	return o.Codes
}

// GetCodesOk returns a tuple with the Codes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MFARecoveryCodesResponse) GetCodesOk() ([]string, bool) {
	if o == nil || IsNil(o.Codes) {
		return nil, false
	}
	return o.Codes, true
}

// HasCodes returns a boolean if a field has been set.
func (o *MFARecoveryCodesResponse) HasCodes() bool {
	if o != nil && !IsNil(o.Codes) {
		return true
	}

	return false
}

// SetCodes gets a reference to the given []string and assigns it to the Codes field.
func (o *MFARecoveryCodesResponse) SetCodes(v []string) {
	o.Codes = v
}

func (o MFARecoveryCodesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MFARecoveryCodesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Codes) {
		toSerialize["codes"] = o.Codes
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MFARecoveryCodesResponse) UnmarshalJSON(data []byte) (err error) {
	varMFARecoveryCodesResponse := _MFARecoveryCodesResponse{}

	err = json.Unmarshal(data, &varMFARecoveryCodesResponse)

	if err != nil {
		return err
	}

	*o = MFARecoveryCodesResponse(varMFARecoveryCodesResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "codes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMFARecoveryCodesResponse struct {
	value *MFARecoveryCodesResponse
	isSet bool
}

func (v NullableMFARecoveryCodesResponse) Get() *MFARecoveryCodesResponse {
	return v.value
}

func (v *NullableMFARecoveryCodesResponse) Set(val *MFARecoveryCodesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMFARecoveryCodesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMFARecoveryCodesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMFARecoveryCodesResponse(val *MFARecoveryCodesResponse) *NullableMFARecoveryCodesResponse {
	return &NullableMFARecoveryCodesResponse{value: val, isSet: true}
}

func (v NullableMFARecoveryCodesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMFARecoveryCodesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


