/*
GateForge IAM API

Public HTTP API for GateForge IAM — OpenID Connect / OAuth2 endpoints at the server root, plus the application JSON API under `/api/v1` (auth, MFA, WebAuthn, tenants, and platform admin). Success responses for `/api/v1` use a `{meta, data}` envelope. OAuth token and userinfo errors use `{error, error_description}`.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the TenantSelectionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenantSelectionResponse{}

// TenantSelectionResponse struct for TenantSelectionResponse
type TenantSelectionResponse struct {
	SelectionRequired bool `json:"selection_required"`
	Tenants []TenantSummary `json:"tenants"`
	SelectionToken string `json:"selection_token"`
	ExpiresIn int32 `json:"expires_in"`
	AdditionalProperties map[string]interface{}
}

type _TenantSelectionResponse TenantSelectionResponse

// NewTenantSelectionResponse instantiates a new TenantSelectionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantSelectionResponse(selectionRequired bool, tenants []TenantSummary, selectionToken string, expiresIn int32) *TenantSelectionResponse {
	this := TenantSelectionResponse{}
	this.SelectionRequired = selectionRequired
	this.Tenants = tenants
	this.SelectionToken = selectionToken
	this.ExpiresIn = expiresIn
	return &this
}

// NewTenantSelectionResponseWithDefaults instantiates a new TenantSelectionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantSelectionResponseWithDefaults() *TenantSelectionResponse {
	this := TenantSelectionResponse{}
	return &this
}

// GetSelectionRequired returns the SelectionRequired field value
func (o *TenantSelectionResponse) GetSelectionRequired() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.SelectionRequired
}

// GetSelectionRequiredOk returns a tuple with the SelectionRequired field value
// and a boolean to check if the value has been set.
func (o *TenantSelectionResponse) GetSelectionRequiredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SelectionRequired, true
}

// SetSelectionRequired sets field value
func (o *TenantSelectionResponse) SetSelectionRequired(v bool) {
	o.SelectionRequired = v
}

// GetTenants returns the Tenants field value
func (o *TenantSelectionResponse) GetTenants() []TenantSummary {
	if o == nil {
		var ret []TenantSummary
		return ret
	}

	return o.Tenants
}

// GetTenantsOk returns a tuple with the Tenants field value
// and a boolean to check if the value has been set.
func (o *TenantSelectionResponse) GetTenantsOk() ([]TenantSummary, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tenants, true
}

// SetTenants sets field value
func (o *TenantSelectionResponse) SetTenants(v []TenantSummary) {
	o.Tenants = v
}

// GetSelectionToken returns the SelectionToken field value
func (o *TenantSelectionResponse) GetSelectionToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SelectionToken
}

// GetSelectionTokenOk returns a tuple with the SelectionToken field value
// and a boolean to check if the value has been set.
func (o *TenantSelectionResponse) GetSelectionTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SelectionToken, true
}

// SetSelectionToken sets field value
func (o *TenantSelectionResponse) SetSelectionToken(v string) {
	o.SelectionToken = v
}

// GetExpiresIn returns the ExpiresIn field value
func (o *TenantSelectionResponse) GetExpiresIn() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ExpiresIn
}

// GetExpiresInOk returns a tuple with the ExpiresIn field value
// and a boolean to check if the value has been set.
func (o *TenantSelectionResponse) GetExpiresInOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresIn, true
}

// SetExpiresIn sets field value
func (o *TenantSelectionResponse) SetExpiresIn(v int32) {
	o.ExpiresIn = v
}

func (o TenantSelectionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenantSelectionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["selection_required"] = o.SelectionRequired
	toSerialize["tenants"] = o.Tenants
	toSerialize["selection_token"] = o.SelectionToken
	toSerialize["expires_in"] = o.ExpiresIn

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TenantSelectionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"selection_required",
		"tenants",
		"selection_token",
		"expires_in",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTenantSelectionResponse := _TenantSelectionResponse{}

	err = json.Unmarshal(data, &varTenantSelectionResponse)

	if err != nil {
		return err
	}

	*o = TenantSelectionResponse(varTenantSelectionResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "selection_required")
		delete(additionalProperties, "tenants")
		delete(additionalProperties, "selection_token")
		delete(additionalProperties, "expires_in")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTenantSelectionResponse struct {
	value *TenantSelectionResponse
	isSet bool
}

func (v NullableTenantSelectionResponse) Get() *TenantSelectionResponse {
	return v.value
}

func (v *NullableTenantSelectionResponse) Set(val *TenantSelectionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantSelectionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantSelectionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantSelectionResponse(val *TenantSelectionResponse) *NullableTenantSelectionResponse {
	return &NullableTenantSelectionResponse{value: val, isSet: true}
}

func (v NullableTenantSelectionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantSelectionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


