/*
GateForge IAM API

Public HTTP API for GateForge IAM — OpenID Connect / OAuth2 endpoints at the server root, plus the application JSON API under `/api/v1` (auth, MFA, WebAuthn, tenants, and platform admin). Success responses for `/api/v1` use a `{meta, data}` envelope. OAuth token and userinfo errors use `{error, error_description}`.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the UserResponseEnvelope type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserResponseEnvelope{}

// UserResponseEnvelope struct for UserResponseEnvelope
type UserResponseEnvelope struct {
	Meta Meta `json:"meta"`
	Data UserResponse `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _UserResponseEnvelope UserResponseEnvelope

// NewUserResponseEnvelope instantiates a new UserResponseEnvelope object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserResponseEnvelope(meta Meta, data UserResponse) *UserResponseEnvelope {
	this := UserResponseEnvelope{}
	this.Meta = meta
	this.Data = data
	return &this
}

// NewUserResponseEnvelopeWithDefaults instantiates a new UserResponseEnvelope object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserResponseEnvelopeWithDefaults() *UserResponseEnvelope {
	this := UserResponseEnvelope{}
	return &this
}

// GetMeta returns the Meta field value
func (o *UserResponseEnvelope) GetMeta() Meta {
	if o == nil {
		var ret Meta
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *UserResponseEnvelope) GetMetaOk() (*Meta, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Meta, true
}

// SetMeta sets field value
func (o *UserResponseEnvelope) SetMeta(v Meta) {
	o.Meta = v
}

// GetData returns the Data field value
func (o *UserResponseEnvelope) GetData() UserResponse {
	if o == nil {
		var ret UserResponse
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UserResponseEnvelope) GetDataOk() (*UserResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UserResponseEnvelope) SetData(v UserResponse) {
	o.Data = v
}

func (o UserResponseEnvelope) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserResponseEnvelope) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["meta"] = o.Meta
	toSerialize["data"] = o.Data

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UserResponseEnvelope) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"meta",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserResponseEnvelope := _UserResponseEnvelope{}

	err = json.Unmarshal(data, &varUserResponseEnvelope)

	if err != nil {
		return err
	}

	*o = UserResponseEnvelope(varUserResponseEnvelope)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "meta")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUserResponseEnvelope struct {
	value *UserResponseEnvelope
	isSet bool
}

func (v NullableUserResponseEnvelope) Get() *UserResponseEnvelope {
	return v.value
}

func (v *NullableUserResponseEnvelope) Set(val *UserResponseEnvelope) {
	v.value = val
	v.isSet = true
}

func (v NullableUserResponseEnvelope) IsSet() bool {
	return v.isSet
}

func (v *NullableUserResponseEnvelope) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserResponseEnvelope(val *UserResponseEnvelope) *NullableUserResponseEnvelope {
	return &NullableUserResponseEnvelope{value: val, isSet: true}
}

func (v NullableUserResponseEnvelope) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserResponseEnvelope) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


