/*
GateForge IAM API

Public HTTP API for GateForge IAM — OpenID Connect / OAuth2 endpoints at the server root, plus the application JSON API under `/api/v1` (auth, MFA, WebAuthn, tenants, and platform admin). Success responses for `/api/v1` use a `{meta, data}` envelope. OAuth token and userinfo errors use `{error, error_description}`.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the MFALoginChallengeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MFALoginChallengeResponse{}

// MFALoginChallengeResponse struct for MFALoginChallengeResponse
type MFALoginChallengeResponse struct {
	MfaRequired bool `json:"mfa_required"`
	MfaTicket string `json:"mfa_ticket"`
	ExpiresIn int32 `json:"expires_in"`
	AdditionalProperties map[string]interface{}
}

type _MFALoginChallengeResponse MFALoginChallengeResponse

// NewMFALoginChallengeResponse instantiates a new MFALoginChallengeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMFALoginChallengeResponse(mfaRequired bool, mfaTicket string, expiresIn int32) *MFALoginChallengeResponse {
	this := MFALoginChallengeResponse{}
	this.MfaRequired = mfaRequired
	this.MfaTicket = mfaTicket
	this.ExpiresIn = expiresIn
	return &this
}

// NewMFALoginChallengeResponseWithDefaults instantiates a new MFALoginChallengeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMFALoginChallengeResponseWithDefaults() *MFALoginChallengeResponse {
	this := MFALoginChallengeResponse{}
	return &this
}

// GetMfaRequired returns the MfaRequired field value
func (o *MFALoginChallengeResponse) GetMfaRequired() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.MfaRequired
}

// GetMfaRequiredOk returns a tuple with the MfaRequired field value
// and a boolean to check if the value has been set.
func (o *MFALoginChallengeResponse) GetMfaRequiredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MfaRequired, true
}

// SetMfaRequired sets field value
func (o *MFALoginChallengeResponse) SetMfaRequired(v bool) {
	o.MfaRequired = v
}

// GetMfaTicket returns the MfaTicket field value
func (o *MFALoginChallengeResponse) GetMfaTicket() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MfaTicket
}

// GetMfaTicketOk returns a tuple with the MfaTicket field value
// and a boolean to check if the value has been set.
func (o *MFALoginChallengeResponse) GetMfaTicketOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MfaTicket, true
}

// SetMfaTicket sets field value
func (o *MFALoginChallengeResponse) SetMfaTicket(v string) {
	o.MfaTicket = v
}

// GetExpiresIn returns the ExpiresIn field value
func (o *MFALoginChallengeResponse) GetExpiresIn() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ExpiresIn
}

// GetExpiresInOk returns a tuple with the ExpiresIn field value
// and a boolean to check if the value has been set.
func (o *MFALoginChallengeResponse) GetExpiresInOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresIn, true
}

// SetExpiresIn sets field value
func (o *MFALoginChallengeResponse) SetExpiresIn(v int32) {
	o.ExpiresIn = v
}

func (o MFALoginChallengeResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MFALoginChallengeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mfa_required"] = o.MfaRequired
	toSerialize["mfa_ticket"] = o.MfaTicket
	toSerialize["expires_in"] = o.ExpiresIn

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MFALoginChallengeResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"mfa_required",
		"mfa_ticket",
		"expires_in",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMFALoginChallengeResponse := _MFALoginChallengeResponse{}

	err = json.Unmarshal(data, &varMFALoginChallengeResponse)

	if err != nil {
		return err
	}

	*o = MFALoginChallengeResponse(varMFALoginChallengeResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "mfa_required")
		delete(additionalProperties, "mfa_ticket")
		delete(additionalProperties, "expires_in")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMFALoginChallengeResponse struct {
	value *MFALoginChallengeResponse
	isSet bool
}

func (v NullableMFALoginChallengeResponse) Get() *MFALoginChallengeResponse {
	return v.value
}

func (v *NullableMFALoginChallengeResponse) Set(val *MFALoginChallengeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMFALoginChallengeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMFALoginChallengeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMFALoginChallengeResponse(val *MFALoginChallengeResponse) *NullableMFALoginChallengeResponse {
	return &NullableMFALoginChallengeResponse{value: val, isSet: true}
}

func (v NullableMFALoginChallengeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMFALoginChallengeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


