/*
GateForge IAM API

Public HTTP API for GateForge IAM — OpenID Connect / OAuth2 endpoints at the server root, plus the application JSON API under `/api/v1` (auth, MFA, WebAuthn, tenants, and platform admin). Success responses for `/api/v1` use a `{meta, data}` envelope. OAuth token and userinfo errors use `{error, error_description}`.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the MFAChallengeVerifyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MFAChallengeVerifyRequest{}

// MFAChallengeVerifyRequest struct for MFAChallengeVerifyRequest
type MFAChallengeVerifyRequest struct {
	Code string `json:"code"`
	MfaTicket string `json:"mfa_ticket"`
	AdditionalProperties map[string]interface{}
}

type _MFAChallengeVerifyRequest MFAChallengeVerifyRequest

// NewMFAChallengeVerifyRequest instantiates a new MFAChallengeVerifyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMFAChallengeVerifyRequest(code string, mfaTicket string) *MFAChallengeVerifyRequest {
	this := MFAChallengeVerifyRequest{}
	this.Code = code
	this.MfaTicket = mfaTicket
	return &this
}

// NewMFAChallengeVerifyRequestWithDefaults instantiates a new MFAChallengeVerifyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMFAChallengeVerifyRequestWithDefaults() *MFAChallengeVerifyRequest {
	this := MFAChallengeVerifyRequest{}
	return &this
}

// GetCode returns the Code field value
func (o *MFAChallengeVerifyRequest) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *MFAChallengeVerifyRequest) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *MFAChallengeVerifyRequest) SetCode(v string) {
	o.Code = v
}

// GetMfaTicket returns the MfaTicket field value
func (o *MFAChallengeVerifyRequest) GetMfaTicket() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MfaTicket
}

// GetMfaTicketOk returns a tuple with the MfaTicket field value
// and a boolean to check if the value has been set.
func (o *MFAChallengeVerifyRequest) GetMfaTicketOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MfaTicket, true
}

// SetMfaTicket sets field value
func (o *MFAChallengeVerifyRequest) SetMfaTicket(v string) {
	o.MfaTicket = v
}

func (o MFAChallengeVerifyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MFAChallengeVerifyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["mfa_ticket"] = o.MfaTicket

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MFAChallengeVerifyRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"mfa_ticket",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMFAChallengeVerifyRequest := _MFAChallengeVerifyRequest{}

	err = json.Unmarshal(data, &varMFAChallengeVerifyRequest)

	if err != nil {
		return err
	}

	*o = MFAChallengeVerifyRequest(varMFAChallengeVerifyRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "code")
		delete(additionalProperties, "mfa_ticket")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMFAChallengeVerifyRequest struct {
	value *MFAChallengeVerifyRequest
	isSet bool
}

func (v NullableMFAChallengeVerifyRequest) Get() *MFAChallengeVerifyRequest {
	return v.value
}

func (v *NullableMFAChallengeVerifyRequest) Set(val *MFAChallengeVerifyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMFAChallengeVerifyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMFAChallengeVerifyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMFAChallengeVerifyRequest(val *MFAChallengeVerifyRequest) *NullableMFAChallengeVerifyRequest {
	return &NullableMFAChallengeVerifyRequest{value: val, isSet: true}
}

func (v NullableMFAChallengeVerifyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMFAChallengeVerifyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


