/*
GateForge IAM API

Public HTTP API for GateForge IAM — OpenID Connect / OAuth2 endpoints at the server root, plus the application JSON API under `/api/v1` (auth, MFA, WebAuthn, tenants, and platform admin). Success responses for `/api/v1` use a `{meta, data}` envelope. OAuth token and userinfo errors use `{error, error_description}`.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the AdminUserDetailResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminUserDetailResponse{}

// AdminUserDetailResponse struct for AdminUserDetailResponse
type AdminUserDetailResponse struct {
	Id *string `json:"id,omitempty"`
	Email *string `json:"email,omitempty"`
	FirstName *string `json:"first_name,omitempty"`
	LastName *string `json:"last_name,omitempty"`
	Status *string `json:"status,omitempty"`
	MfaEnabled *bool `json:"mfa_enabled,omitempty"`
	IsPlatformAdmin *bool `json:"is_platform_admin,omitempty"`
	PasskeyCount *int32 `json:"passkey_count,omitempty"`
	ActiveSessions *int32 `json:"active_sessions,omitempty"`
	Memberships []AdminUserMembershipResponse `json:"memberships,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AdminUserDetailResponse AdminUserDetailResponse

// NewAdminUserDetailResponse instantiates a new AdminUserDetailResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminUserDetailResponse() *AdminUserDetailResponse {
	this := AdminUserDetailResponse{}
	return &this
}

// NewAdminUserDetailResponseWithDefaults instantiates a new AdminUserDetailResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminUserDetailResponseWithDefaults() *AdminUserDetailResponse {
	this := AdminUserDetailResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AdminUserDetailResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminUserDetailResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AdminUserDetailResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *AdminUserDetailResponse) SetId(v string) {
	o.Id = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *AdminUserDetailResponse) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminUserDetailResponse) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *AdminUserDetailResponse) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *AdminUserDetailResponse) SetEmail(v string) {
	o.Email = &v
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *AdminUserDetailResponse) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminUserDetailResponse) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *AdminUserDetailResponse) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *AdminUserDetailResponse) SetFirstName(v string) {
	o.FirstName = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *AdminUserDetailResponse) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminUserDetailResponse) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *AdminUserDetailResponse) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *AdminUserDetailResponse) SetLastName(v string) {
	o.LastName = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *AdminUserDetailResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminUserDetailResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *AdminUserDetailResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *AdminUserDetailResponse) SetStatus(v string) {
	o.Status = &v
}

// GetMfaEnabled returns the MfaEnabled field value if set, zero value otherwise.
func (o *AdminUserDetailResponse) GetMfaEnabled() bool {
	if o == nil || IsNil(o.MfaEnabled) {
		var ret bool
		return ret
	}
	return *o.MfaEnabled
}

// GetMfaEnabledOk returns a tuple with the MfaEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminUserDetailResponse) GetMfaEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.MfaEnabled) {
		return nil, false
	}
	return o.MfaEnabled, true
}

// HasMfaEnabled returns a boolean if a field has been set.
func (o *AdminUserDetailResponse) HasMfaEnabled() bool {
	if o != nil && !IsNil(o.MfaEnabled) {
		return true
	}

	return false
}

// SetMfaEnabled gets a reference to the given bool and assigns it to the MfaEnabled field.
func (o *AdminUserDetailResponse) SetMfaEnabled(v bool) {
	o.MfaEnabled = &v
}

// GetIsPlatformAdmin returns the IsPlatformAdmin field value if set, zero value otherwise.
func (o *AdminUserDetailResponse) GetIsPlatformAdmin() bool {
	if o == nil || IsNil(o.IsPlatformAdmin) {
		var ret bool
		return ret
	}
	return *o.IsPlatformAdmin
}

// GetIsPlatformAdminOk returns a tuple with the IsPlatformAdmin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminUserDetailResponse) GetIsPlatformAdminOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPlatformAdmin) {
		return nil, false
	}
	return o.IsPlatformAdmin, true
}

// HasIsPlatformAdmin returns a boolean if a field has been set.
func (o *AdminUserDetailResponse) HasIsPlatformAdmin() bool {
	if o != nil && !IsNil(o.IsPlatformAdmin) {
		return true
	}

	return false
}

// SetIsPlatformAdmin gets a reference to the given bool and assigns it to the IsPlatformAdmin field.
func (o *AdminUserDetailResponse) SetIsPlatformAdmin(v bool) {
	o.IsPlatformAdmin = &v
}

// GetPasskeyCount returns the PasskeyCount field value if set, zero value otherwise.
func (o *AdminUserDetailResponse) GetPasskeyCount() int32 {
	if o == nil || IsNil(o.PasskeyCount) {
		var ret int32
		return ret
	}
	return *o.PasskeyCount
}

// GetPasskeyCountOk returns a tuple with the PasskeyCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminUserDetailResponse) GetPasskeyCountOk() (*int32, bool) {
	if o == nil || IsNil(o.PasskeyCount) {
		return nil, false
	}
	return o.PasskeyCount, true
}

// HasPasskeyCount returns a boolean if a field has been set.
func (o *AdminUserDetailResponse) HasPasskeyCount() bool {
	if o != nil && !IsNil(o.PasskeyCount) {
		return true
	}

	return false
}

// SetPasskeyCount gets a reference to the given int32 and assigns it to the PasskeyCount field.
func (o *AdminUserDetailResponse) SetPasskeyCount(v int32) {
	o.PasskeyCount = &v
}

// GetActiveSessions returns the ActiveSessions field value if set, zero value otherwise.
func (o *AdminUserDetailResponse) GetActiveSessions() int32 {
	if o == nil || IsNil(o.ActiveSessions) {
		var ret int32
		return ret
	}
	return *o.ActiveSessions
}

// GetActiveSessionsOk returns a tuple with the ActiveSessions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminUserDetailResponse) GetActiveSessionsOk() (*int32, bool) {
	if o == nil || IsNil(o.ActiveSessions) {
		return nil, false
	}
	return o.ActiveSessions, true
}

// HasActiveSessions returns a boolean if a field has been set.
func (o *AdminUserDetailResponse) HasActiveSessions() bool {
	if o != nil && !IsNil(o.ActiveSessions) {
		return true
	}

	return false
}

// SetActiveSessions gets a reference to the given int32 and assigns it to the ActiveSessions field.
func (o *AdminUserDetailResponse) SetActiveSessions(v int32) {
	o.ActiveSessions = &v
}

// GetMemberships returns the Memberships field value if set, zero value otherwise.
func (o *AdminUserDetailResponse) GetMemberships() []AdminUserMembershipResponse {
	if o == nil || IsNil(o.Memberships) {
		var ret []AdminUserMembershipResponse
		return ret
	}
	return o.Memberships
}

// GetMembershipsOk returns a tuple with the Memberships field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminUserDetailResponse) GetMembershipsOk() ([]AdminUserMembershipResponse, bool) {
	if o == nil || IsNil(o.Memberships) {
		return nil, false
	}
	return o.Memberships, true
}

// HasMemberships returns a boolean if a field has been set.
func (o *AdminUserDetailResponse) HasMemberships() bool {
	if o != nil && !IsNil(o.Memberships) {
		return true
	}

	return false
}

// SetMemberships gets a reference to the given []AdminUserMembershipResponse and assigns it to the Memberships field.
func (o *AdminUserDetailResponse) SetMemberships(v []AdminUserMembershipResponse) {
	o.Memberships = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *AdminUserDetailResponse) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminUserDetailResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *AdminUserDetailResponse) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *AdminUserDetailResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

func (o AdminUserDetailResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminUserDetailResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.FirstName) {
		toSerialize["first_name"] = o.FirstName
	}
	if !IsNil(o.LastName) {
		toSerialize["last_name"] = o.LastName
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.MfaEnabled) {
		toSerialize["mfa_enabled"] = o.MfaEnabled
	}
	if !IsNil(o.IsPlatformAdmin) {
		toSerialize["is_platform_admin"] = o.IsPlatformAdmin
	}
	if !IsNil(o.PasskeyCount) {
		toSerialize["passkey_count"] = o.PasskeyCount
	}
	if !IsNil(o.ActiveSessions) {
		toSerialize["active_sessions"] = o.ActiveSessions
	}
	if !IsNil(o.Memberships) {
		toSerialize["memberships"] = o.Memberships
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AdminUserDetailResponse) UnmarshalJSON(data []byte) (err error) {
	varAdminUserDetailResponse := _AdminUserDetailResponse{}

	err = json.Unmarshal(data, &varAdminUserDetailResponse)

	if err != nil {
		return err
	}

	*o = AdminUserDetailResponse(varAdminUserDetailResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "email")
		delete(additionalProperties, "first_name")
		delete(additionalProperties, "last_name")
		delete(additionalProperties, "status")
		delete(additionalProperties, "mfa_enabled")
		delete(additionalProperties, "is_platform_admin")
		delete(additionalProperties, "passkey_count")
		delete(additionalProperties, "active_sessions")
		delete(additionalProperties, "memberships")
		delete(additionalProperties, "created_at")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAdminUserDetailResponse struct {
	value *AdminUserDetailResponse
	isSet bool
}

func (v NullableAdminUserDetailResponse) Get() *AdminUserDetailResponse {
	return v.value
}

func (v *NullableAdminUserDetailResponse) Set(val *AdminUserDetailResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminUserDetailResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminUserDetailResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminUserDetailResponse(val *AdminUserDetailResponse) *NullableAdminUserDetailResponse {
	return &NullableAdminUserDetailResponse{value: val, isSet: true}
}

func (v NullableAdminUserDetailResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminUserDetailResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


