/*
GateForge IAM API

Public HTTP API for GateForge IAM — OpenID Connect / OAuth2 endpoints at the server root, plus the application JSON API under `/api/v1` (auth, MFA, WebAuthn, tenants, and platform admin). Success responses for `/api/v1` use a `{meta, data}` envelope. OAuth token and userinfo errors use `{error, error_description}`.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the AdminClientUsageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminClientUsageResponse{}

// AdminClientUsageResponse struct for AdminClientUsageResponse
type AdminClientUsageResponse struct {
	ClientId *string `json:"client_id,omitempty"`
	ActiveRefreshTokens *int32 `json:"active_refresh_tokens,omitempty"`
	TotalRefreshTokens *int32 `json:"total_refresh_tokens,omitempty"`
	AuthorizeEvents30d *int32 `json:"authorize_events_30d,omitempty"`
	TokenIssueEvents30d *int32 `json:"token_issue_events_30d,omitempty"`
	LastTokenIssuedAt *time.Time `json:"last_token_issued_at,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AdminClientUsageResponse AdminClientUsageResponse

// NewAdminClientUsageResponse instantiates a new AdminClientUsageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminClientUsageResponse() *AdminClientUsageResponse {
	this := AdminClientUsageResponse{}
	return &this
}

// NewAdminClientUsageResponseWithDefaults instantiates a new AdminClientUsageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminClientUsageResponseWithDefaults() *AdminClientUsageResponse {
	this := AdminClientUsageResponse{}
	return &this
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *AdminClientUsageResponse) GetClientId() string {
	if o == nil || IsNil(o.ClientId) {
		var ret string
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminClientUsageResponse) GetClientIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClientId) {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *AdminClientUsageResponse) HasClientId() bool {
	if o != nil && !IsNil(o.ClientId) {
		return true
	}

	return false
}

// SetClientId gets a reference to the given string and assigns it to the ClientId field.
func (o *AdminClientUsageResponse) SetClientId(v string) {
	o.ClientId = &v
}

// GetActiveRefreshTokens returns the ActiveRefreshTokens field value if set, zero value otherwise.
func (o *AdminClientUsageResponse) GetActiveRefreshTokens() int32 {
	if o == nil || IsNil(o.ActiveRefreshTokens) {
		var ret int32
		return ret
	}
	return *o.ActiveRefreshTokens
}

// GetActiveRefreshTokensOk returns a tuple with the ActiveRefreshTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminClientUsageResponse) GetActiveRefreshTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.ActiveRefreshTokens) {
		return nil, false
	}
	return o.ActiveRefreshTokens, true
}

// HasActiveRefreshTokens returns a boolean if a field has been set.
func (o *AdminClientUsageResponse) HasActiveRefreshTokens() bool {
	if o != nil && !IsNil(o.ActiveRefreshTokens) {
		return true
	}

	return false
}

// SetActiveRefreshTokens gets a reference to the given int32 and assigns it to the ActiveRefreshTokens field.
func (o *AdminClientUsageResponse) SetActiveRefreshTokens(v int32) {
	o.ActiveRefreshTokens = &v
}

// GetTotalRefreshTokens returns the TotalRefreshTokens field value if set, zero value otherwise.
func (o *AdminClientUsageResponse) GetTotalRefreshTokens() int32 {
	if o == nil || IsNil(o.TotalRefreshTokens) {
		var ret int32
		return ret
	}
	return *o.TotalRefreshTokens
}

// GetTotalRefreshTokensOk returns a tuple with the TotalRefreshTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminClientUsageResponse) GetTotalRefreshTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalRefreshTokens) {
		return nil, false
	}
	return o.TotalRefreshTokens, true
}

// HasTotalRefreshTokens returns a boolean if a field has been set.
func (o *AdminClientUsageResponse) HasTotalRefreshTokens() bool {
	if o != nil && !IsNil(o.TotalRefreshTokens) {
		return true
	}

	return false
}

// SetTotalRefreshTokens gets a reference to the given int32 and assigns it to the TotalRefreshTokens field.
func (o *AdminClientUsageResponse) SetTotalRefreshTokens(v int32) {
	o.TotalRefreshTokens = &v
}

// GetAuthorizeEvents30d returns the AuthorizeEvents30d field value if set, zero value otherwise.
func (o *AdminClientUsageResponse) GetAuthorizeEvents30d() int32 {
	if o == nil || IsNil(o.AuthorizeEvents30d) {
		var ret int32
		return ret
	}
	return *o.AuthorizeEvents30d
}

// GetAuthorizeEvents30dOk returns a tuple with the AuthorizeEvents30d field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminClientUsageResponse) GetAuthorizeEvents30dOk() (*int32, bool) {
	if o == nil || IsNil(o.AuthorizeEvents30d) {
		return nil, false
	}
	return o.AuthorizeEvents30d, true
}

// HasAuthorizeEvents30d returns a boolean if a field has been set.
func (o *AdminClientUsageResponse) HasAuthorizeEvents30d() bool {
	if o != nil && !IsNil(o.AuthorizeEvents30d) {
		return true
	}

	return false
}

// SetAuthorizeEvents30d gets a reference to the given int32 and assigns it to the AuthorizeEvents30d field.
func (o *AdminClientUsageResponse) SetAuthorizeEvents30d(v int32) {
	o.AuthorizeEvents30d = &v
}

// GetTokenIssueEvents30d returns the TokenIssueEvents30d field value if set, zero value otherwise.
func (o *AdminClientUsageResponse) GetTokenIssueEvents30d() int32 {
	if o == nil || IsNil(o.TokenIssueEvents30d) {
		var ret int32
		return ret
	}
	return *o.TokenIssueEvents30d
}

// GetTokenIssueEvents30dOk returns a tuple with the TokenIssueEvents30d field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminClientUsageResponse) GetTokenIssueEvents30dOk() (*int32, bool) {
	if o == nil || IsNil(o.TokenIssueEvents30d) {
		return nil, false
	}
	return o.TokenIssueEvents30d, true
}

// HasTokenIssueEvents30d returns a boolean if a field has been set.
func (o *AdminClientUsageResponse) HasTokenIssueEvents30d() bool {
	if o != nil && !IsNil(o.TokenIssueEvents30d) {
		return true
	}

	return false
}

// SetTokenIssueEvents30d gets a reference to the given int32 and assigns it to the TokenIssueEvents30d field.
func (o *AdminClientUsageResponse) SetTokenIssueEvents30d(v int32) {
	o.TokenIssueEvents30d = &v
}

// GetLastTokenIssuedAt returns the LastTokenIssuedAt field value if set, zero value otherwise.
func (o *AdminClientUsageResponse) GetLastTokenIssuedAt() time.Time {
	if o == nil || IsNil(o.LastTokenIssuedAt) {
		var ret time.Time
		return ret
	}
	return *o.LastTokenIssuedAt
}

// GetLastTokenIssuedAtOk returns a tuple with the LastTokenIssuedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminClientUsageResponse) GetLastTokenIssuedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastTokenIssuedAt) {
		return nil, false
	}
	return o.LastTokenIssuedAt, true
}

// HasLastTokenIssuedAt returns a boolean if a field has been set.
func (o *AdminClientUsageResponse) HasLastTokenIssuedAt() bool {
	if o != nil && !IsNil(o.LastTokenIssuedAt) {
		return true
	}

	return false
}

// SetLastTokenIssuedAt gets a reference to the given time.Time and assigns it to the LastTokenIssuedAt field.
func (o *AdminClientUsageResponse) SetLastTokenIssuedAt(v time.Time) {
	o.LastTokenIssuedAt = &v
}

func (o AdminClientUsageResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminClientUsageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ClientId) {
		toSerialize["client_id"] = o.ClientId
	}
	if !IsNil(o.ActiveRefreshTokens) {
		toSerialize["active_refresh_tokens"] = o.ActiveRefreshTokens
	}
	if !IsNil(o.TotalRefreshTokens) {
		toSerialize["total_refresh_tokens"] = o.TotalRefreshTokens
	}
	if !IsNil(o.AuthorizeEvents30d) {
		toSerialize["authorize_events_30d"] = o.AuthorizeEvents30d
	}
	if !IsNil(o.TokenIssueEvents30d) {
		toSerialize["token_issue_events_30d"] = o.TokenIssueEvents30d
	}
	if !IsNil(o.LastTokenIssuedAt) {
		toSerialize["last_token_issued_at"] = o.LastTokenIssuedAt
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AdminClientUsageResponse) UnmarshalJSON(data []byte) (err error) {
	varAdminClientUsageResponse := _AdminClientUsageResponse{}

	err = json.Unmarshal(data, &varAdminClientUsageResponse)

	if err != nil {
		return err
	}

	*o = AdminClientUsageResponse(varAdminClientUsageResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "client_id")
		delete(additionalProperties, "active_refresh_tokens")
		delete(additionalProperties, "total_refresh_tokens")
		delete(additionalProperties, "authorize_events_30d")
		delete(additionalProperties, "token_issue_events_30d")
		delete(additionalProperties, "last_token_issued_at")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAdminClientUsageResponse struct {
	value *AdminClientUsageResponse
	isSet bool
}

func (v NullableAdminClientUsageResponse) Get() *AdminClientUsageResponse {
	return v.value
}

func (v *NullableAdminClientUsageResponse) Set(val *AdminClientUsageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminClientUsageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminClientUsageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminClientUsageResponse(val *AdminClientUsageResponse) *NullableAdminClientUsageResponse {
	return &NullableAdminClientUsageResponse{value: val, isSet: true}
}

func (v NullableAdminClientUsageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminClientUsageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


