/*
GateForge IAM API

Public HTTP API for GateForge IAM — OpenID Connect / OAuth2 endpoints at the server root, plus the application JSON API under `/api/v1` (auth, MFA, WebAuthn, tenants, and platform admin). Success responses for `/api/v1` use a `{meta, data}` envelope. OAuth token and userinfo errors use `{error, error_description}`.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the WebauthnRegisterFinishRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebauthnRegisterFinishRequest{}

// WebauthnRegisterFinishRequest struct for WebauthnRegisterFinishRequest
type WebauthnRegisterFinishRequest struct {
	SessionToken string `json:"session_token"`
	// PublicKeyCredential JSON from navigator.credentials.create()
	Credential map[string]interface{} `json:"credential,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _WebauthnRegisterFinishRequest WebauthnRegisterFinishRequest

// NewWebauthnRegisterFinishRequest instantiates a new WebauthnRegisterFinishRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebauthnRegisterFinishRequest(sessionToken string) *WebauthnRegisterFinishRequest {
	this := WebauthnRegisterFinishRequest{}
	this.SessionToken = sessionToken
	return &this
}

// NewWebauthnRegisterFinishRequestWithDefaults instantiates a new WebauthnRegisterFinishRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebauthnRegisterFinishRequestWithDefaults() *WebauthnRegisterFinishRequest {
	this := WebauthnRegisterFinishRequest{}
	return &this
}

// GetSessionToken returns the SessionToken field value
func (o *WebauthnRegisterFinishRequest) GetSessionToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SessionToken
}

// GetSessionTokenOk returns a tuple with the SessionToken field value
// and a boolean to check if the value has been set.
func (o *WebauthnRegisterFinishRequest) GetSessionTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionToken, true
}

// SetSessionToken sets field value
func (o *WebauthnRegisterFinishRequest) SetSessionToken(v string) {
	o.SessionToken = v
}

// GetCredential returns the Credential field value if set, zero value otherwise.
func (o *WebauthnRegisterFinishRequest) GetCredential() map[string]interface{} {
	if o == nil || IsNil(o.Credential) {
		var ret map[string]interface{}
		return ret
	}
	return o.Credential
}

// GetCredentialOk returns a tuple with the Credential field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebauthnRegisterFinishRequest) GetCredentialOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Credential) {
		return map[string]interface{}{}, false
	}
	return o.Credential, true
}

// HasCredential returns a boolean if a field has been set.
func (o *WebauthnRegisterFinishRequest) HasCredential() bool {
	if o != nil && !IsNil(o.Credential) {
		return true
	}

	return false
}

// SetCredential gets a reference to the given map[string]interface{} and assigns it to the Credential field.
func (o *WebauthnRegisterFinishRequest) SetCredential(v map[string]interface{}) {
	o.Credential = v
}

func (o WebauthnRegisterFinishRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebauthnRegisterFinishRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["session_token"] = o.SessionToken
	if !IsNil(o.Credential) {
		toSerialize["credential"] = o.Credential
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WebauthnRegisterFinishRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"session_token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebauthnRegisterFinishRequest := _WebauthnRegisterFinishRequest{}

	err = json.Unmarshal(data, &varWebauthnRegisterFinishRequest)

	if err != nil {
		return err
	}

	*o = WebauthnRegisterFinishRequest(varWebauthnRegisterFinishRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "session_token")
		delete(additionalProperties, "credential")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWebauthnRegisterFinishRequest struct {
	value *WebauthnRegisterFinishRequest
	isSet bool
}

func (v NullableWebauthnRegisterFinishRequest) Get() *WebauthnRegisterFinishRequest {
	return v.value
}

func (v *NullableWebauthnRegisterFinishRequest) Set(val *WebauthnRegisterFinishRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWebauthnRegisterFinishRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWebauthnRegisterFinishRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebauthnRegisterFinishRequest(val *WebauthnRegisterFinishRequest) *NullableWebauthnRegisterFinishRequest {
	return &NullableWebauthnRegisterFinishRequest{value: val, isSet: true}
}

func (v NullableWebauthnRegisterFinishRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebauthnRegisterFinishRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


