/*
GateForge IAM API

Public HTTP API for GateForge IAM — OpenID Connect / OAuth2 endpoints at the server root, plus the application JSON API under `/api/v1` (auth, MFA, WebAuthn, tenants, and platform admin). Success responses for `/api/v1` use a `{meta, data}` envelope. OAuth token and userinfo errors use `{error, error_description}`.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the TenantSwitchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenantSwitchRequest{}

// TenantSwitchRequest struct for TenantSwitchRequest
type TenantSwitchRequest struct {
	TenantId string `json:"tenant_id"`
	AdditionalProperties map[string]interface{}
}

type _TenantSwitchRequest TenantSwitchRequest

// NewTenantSwitchRequest instantiates a new TenantSwitchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantSwitchRequest(tenantId string) *TenantSwitchRequest {
	this := TenantSwitchRequest{}
	this.TenantId = tenantId
	return &this
}

// NewTenantSwitchRequestWithDefaults instantiates a new TenantSwitchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantSwitchRequestWithDefaults() *TenantSwitchRequest {
	this := TenantSwitchRequest{}
	return &this
}

// GetTenantId returns the TenantId field value
func (o *TenantSwitchRequest) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *TenantSwitchRequest) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *TenantSwitchRequest) SetTenantId(v string) {
	o.TenantId = v
}

func (o TenantSwitchRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenantSwitchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenant_id"] = o.TenantId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TenantSwitchRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenant_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTenantSwitchRequest := _TenantSwitchRequest{}

	err = json.Unmarshal(data, &varTenantSwitchRequest)

	if err != nil {
		return err
	}

	*o = TenantSwitchRequest(varTenantSwitchRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tenant_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTenantSwitchRequest struct {
	value *TenantSwitchRequest
	isSet bool
}

func (v NullableTenantSwitchRequest) Get() *TenantSwitchRequest {
	return v.value
}

func (v *NullableTenantSwitchRequest) Set(val *TenantSwitchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantSwitchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantSwitchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantSwitchRequest(val *TenantSwitchRequest) *NullableTenantSwitchRequest {
	return &NullableTenantSwitchRequest{value: val, isSet: true}
}

func (v NullableTenantSwitchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantSwitchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


