/*
GateForge IAM API

Public HTTP API for GateForge IAM — OpenID Connect / OAuth2 endpoints at the server root, plus the application JSON API under `/api/v1` (auth, MFA, WebAuthn, tenants, and platform admin). Success responses for `/api/v1` use a `{meta, data}` envelope. OAuth token and userinfo errors use `{error, error_description}`.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the AdminTenantEnvelope type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminTenantEnvelope{}

// AdminTenantEnvelope struct for AdminTenantEnvelope
type AdminTenantEnvelope struct {
	Meta Meta `json:"meta"`
	Data AdminTenantResponse `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _AdminTenantEnvelope AdminTenantEnvelope

// NewAdminTenantEnvelope instantiates a new AdminTenantEnvelope object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminTenantEnvelope(meta Meta, data AdminTenantResponse) *AdminTenantEnvelope {
	this := AdminTenantEnvelope{}
	this.Meta = meta
	this.Data = data
	return &this
}

// NewAdminTenantEnvelopeWithDefaults instantiates a new AdminTenantEnvelope object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminTenantEnvelopeWithDefaults() *AdminTenantEnvelope {
	this := AdminTenantEnvelope{}
	return &this
}

// GetMeta returns the Meta field value
func (o *AdminTenantEnvelope) GetMeta() Meta {
	if o == nil {
		var ret Meta
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *AdminTenantEnvelope) GetMetaOk() (*Meta, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Meta, true
}

// SetMeta sets field value
func (o *AdminTenantEnvelope) SetMeta(v Meta) {
	o.Meta = v
}

// GetData returns the Data field value
func (o *AdminTenantEnvelope) GetData() AdminTenantResponse {
	if o == nil {
		var ret AdminTenantResponse
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AdminTenantEnvelope) GetDataOk() (*AdminTenantResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *AdminTenantEnvelope) SetData(v AdminTenantResponse) {
	o.Data = v
}

func (o AdminTenantEnvelope) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminTenantEnvelope) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["meta"] = o.Meta
	toSerialize["data"] = o.Data

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AdminTenantEnvelope) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"meta",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdminTenantEnvelope := _AdminTenantEnvelope{}

	err = json.Unmarshal(data, &varAdminTenantEnvelope)

	if err != nil {
		return err
	}

	*o = AdminTenantEnvelope(varAdminTenantEnvelope)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "meta")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAdminTenantEnvelope struct {
	value *AdminTenantEnvelope
	isSet bool
}

func (v NullableAdminTenantEnvelope) Get() *AdminTenantEnvelope {
	return v.value
}

func (v *NullableAdminTenantEnvelope) Set(val *AdminTenantEnvelope) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminTenantEnvelope) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminTenantEnvelope) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminTenantEnvelope(val *AdminTenantEnvelope) *NullableAdminTenantEnvelope {
	return &NullableAdminTenantEnvelope{value: val, isSet: true}
}

func (v NullableAdminTenantEnvelope) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminTenantEnvelope) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


