/*
GateForge IAM API

Public HTTP API for GateForge IAM — OpenID Connect / OAuth2 endpoints at the server root, plus the application JSON API under `/api/v1` (auth, MFA, WebAuthn, tenants, and platform admin). Success responses for `/api/v1` use a `{meta, data}` envelope. OAuth token and userinfo errors use `{error, error_description}`.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the AdminAddMemberRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminAddMemberRequest{}

// AdminAddMemberRequest struct for AdminAddMemberRequest
type AdminAddMemberRequest struct {
	Email string `json:"email"`
	Role *string `json:"role,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AdminAddMemberRequest AdminAddMemberRequest

// NewAdminAddMemberRequest instantiates a new AdminAddMemberRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminAddMemberRequest(email string) *AdminAddMemberRequest {
	this := AdminAddMemberRequest{}
	this.Email = email
	return &this
}

// NewAdminAddMemberRequestWithDefaults instantiates a new AdminAddMemberRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminAddMemberRequestWithDefaults() *AdminAddMemberRequest {
	this := AdminAddMemberRequest{}
	return &this
}

// GetEmail returns the Email field value
func (o *AdminAddMemberRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *AdminAddMemberRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *AdminAddMemberRequest) SetEmail(v string) {
	o.Email = v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *AdminAddMemberRequest) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminAddMemberRequest) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *AdminAddMemberRequest) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *AdminAddMemberRequest) SetRole(v string) {
	o.Role = &v
}

func (o AdminAddMemberRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminAddMemberRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AdminAddMemberRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdminAddMemberRequest := _AdminAddMemberRequest{}

	err = json.Unmarshal(data, &varAdminAddMemberRequest)

	if err != nil {
		return err
	}

	*o = AdminAddMemberRequest(varAdminAddMemberRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "email")
		delete(additionalProperties, "role")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAdminAddMemberRequest struct {
	value *AdminAddMemberRequest
	isSet bool
}

func (v NullableAdminAddMemberRequest) Get() *AdminAddMemberRequest {
	return v.value
}

func (v *NullableAdminAddMemberRequest) Set(val *AdminAddMemberRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminAddMemberRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminAddMemberRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminAddMemberRequest(val *AdminAddMemberRequest) *NullableAdminAddMemberRequest {
	return &NullableAdminAddMemberRequest{value: val, isSet: true}
}

func (v NullableAdminAddMemberRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminAddMemberRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


