/*
GateForge IAM API

Public HTTP API for GateForge IAM — OpenID Connect / OAuth2 endpoints at the server root, plus the application JSON API under `/api/v1` (auth, MFA, WebAuthn, tenants, and platform admin). Success responses for `/api/v1` use a `{meta, data}` envelope. OAuth token and userinfo errors use `{error, error_description}`.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ErrorEnvelope type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ErrorEnvelope{}

// ErrorEnvelope App API error response
type ErrorEnvelope struct {
	Meta Meta `json:"meta"`
	Data interface{} `json:"data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ErrorEnvelope ErrorEnvelope

// NewErrorEnvelope instantiates a new ErrorEnvelope object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewErrorEnvelope(meta Meta) *ErrorEnvelope {
	this := ErrorEnvelope{}
	this.Meta = meta
	return &this
}

// NewErrorEnvelopeWithDefaults instantiates a new ErrorEnvelope object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewErrorEnvelopeWithDefaults() *ErrorEnvelope {
	this := ErrorEnvelope{}
	return &this
}

// GetMeta returns the Meta field value
func (o *ErrorEnvelope) GetMeta() Meta {
	if o == nil {
		var ret Meta
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *ErrorEnvelope) GetMetaOk() (*Meta, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Meta, true
}

// SetMeta sets field value
func (o *ErrorEnvelope) SetMeta(v Meta) {
	o.Meta = v
}

// GetData returns the Data field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ErrorEnvelope) GetData() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ErrorEnvelope) GetDataOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return &o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ErrorEnvelope) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given interface{} and assigns it to the Data field.
func (o *ErrorEnvelope) SetData(v interface{}) {
	o.Data = v
}

func (o ErrorEnvelope) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ErrorEnvelope) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["meta"] = o.Meta
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ErrorEnvelope) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"meta",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varErrorEnvelope := _ErrorEnvelope{}

	err = json.Unmarshal(data, &varErrorEnvelope)

	if err != nil {
		return err
	}

	*o = ErrorEnvelope(varErrorEnvelope)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "meta")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableErrorEnvelope struct {
	value *ErrorEnvelope
	isSet bool
}

func (v NullableErrorEnvelope) Get() *ErrorEnvelope {
	return v.value
}

func (v *NullableErrorEnvelope) Set(val *ErrorEnvelope) {
	v.value = val
	v.isSet = true
}

func (v NullableErrorEnvelope) IsSet() bool {
	return v.isSet
}

func (v *NullableErrorEnvelope) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErrorEnvelope(val *ErrorEnvelope) *NullableErrorEnvelope {
	return &NullableErrorEnvelope{value: val, isSet: true}
}

func (v NullableErrorEnvelope) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErrorEnvelope) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


