/*
GateForge IAM API

Public HTTP API for GateForge IAM — OpenID Connect / OAuth2 endpoints at the server root, plus the application JSON API under `/api/v1` (auth, MFA, WebAuthn, tenants, and platform admin). Success responses for `/api/v1` use a `{meta, data}` envelope. OAuth token and userinfo errors use `{error, error_description}`.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AdminUpdateTenantRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminUpdateTenantRequest{}

// AdminUpdateTenantRequest struct for AdminUpdateTenantRequest
type AdminUpdateTenantRequest struct {
	Name *string `json:"name,omitempty"`
	Domain *string `json:"domain,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AdminUpdateTenantRequest AdminUpdateTenantRequest

// NewAdminUpdateTenantRequest instantiates a new AdminUpdateTenantRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminUpdateTenantRequest() *AdminUpdateTenantRequest {
	this := AdminUpdateTenantRequest{}
	return &this
}

// NewAdminUpdateTenantRequestWithDefaults instantiates a new AdminUpdateTenantRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminUpdateTenantRequestWithDefaults() *AdminUpdateTenantRequest {
	this := AdminUpdateTenantRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AdminUpdateTenantRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminUpdateTenantRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AdminUpdateTenantRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AdminUpdateTenantRequest) SetName(v string) {
	o.Name = &v
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *AdminUpdateTenantRequest) GetDomain() string {
	if o == nil || IsNil(o.Domain) {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminUpdateTenantRequest) GetDomainOk() (*string, bool) {
	if o == nil || IsNil(o.Domain) {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *AdminUpdateTenantRequest) HasDomain() bool {
	if o != nil && !IsNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *AdminUpdateTenantRequest) SetDomain(v string) {
	o.Domain = &v
}

func (o AdminUpdateTenantRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminUpdateTenantRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Domain) {
		toSerialize["domain"] = o.Domain
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AdminUpdateTenantRequest) UnmarshalJSON(data []byte) (err error) {
	varAdminUpdateTenantRequest := _AdminUpdateTenantRequest{}

	err = json.Unmarshal(data, &varAdminUpdateTenantRequest)

	if err != nil {
		return err
	}

	*o = AdminUpdateTenantRequest(varAdminUpdateTenantRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "domain")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAdminUpdateTenantRequest struct {
	value *AdminUpdateTenantRequest
	isSet bool
}

func (v NullableAdminUpdateTenantRequest) Get() *AdminUpdateTenantRequest {
	return v.value
}

func (v *NullableAdminUpdateTenantRequest) Set(val *AdminUpdateTenantRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminUpdateTenantRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminUpdateTenantRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminUpdateTenantRequest(val *AdminUpdateTenantRequest) *NullableAdminUpdateTenantRequest {
	return &NullableAdminUpdateTenantRequest{value: val, isSet: true}
}

func (v NullableAdminUpdateTenantRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminUpdateTenantRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


